### ISSUE TITLE
Custom number formatting

### ISSUE THREAD

**Issue by toydestroyer** [floere/phony#214]
Hello.

Here in Russia we have [common number format](http://www.artlebedev.com/mandership/91/) like `+7 123 456-78-90` or `+7 12345 6-78-90` (depends on region). Also someone uses these entries: `+7 (123) 456-78-90` and `(+7 123) 456-78-90`.

As you can see we can't get this format with `:spaces` and the only solution to get that is split number and then parse.

So i thought to add few predefined formats like those. Will it pertinently? What do you think about it?

I consider that Russia is not only country with same common formats.

**Comment by floere** [comment]
Merry Christmas ;)

**Comment by floere** [comment]
FYI With 2.10.0, Russian numbers have a local space character of '-' by default.
