### ISSUE TITLE
Not validating some Liberian numbers

### ISSUE THREAD

**Issue by sconstantinides** [floere/phony#216]
Some Liberian numbers don't appear to work, for example these should be valid: "1-231-77-322-333" and "1-231-77-070-1030"

**Comment by toydestroyer** [comment]
Hi,
is it the local format?

I found [this information](http://www.howtocallabroad.com/liberia/) so Liberian numbers should look like `+231-77-322-333`

**Comment by sconstantinides** [comment]
Sorry, looks like you're correct on the first one. But "+231 (0) 77-070-1030" should also be a valid number. I don't have a document to back this up, just personal experience...

**Comment by toydestroyer** [comment]
Could you please provide some information about this format from reliable source?

If believe to [first link in Google](http://www.howtocallabroad.com/liberia/) then number should be 7-8 digits after `+231` (where first digit should be `4`, `5`, `6` or `7`).

In yours example number starts with `0` and contains 10 digits.

**Comment by floere** [comment]
@toydestroyer @sconstantinides Thanks for the help :)

@sconstantinides Are you sure it's a double 7? This lists a single seven, followed by a 3-4 grouping: http://en.wikipedia.org/wiki/Telephone_numbers_in_Liberia

**Comment by sconstantinides** [comment]
Yep, here's another example: http://monrovia.usembassy.gov/contact.html

However, you may need a 0 before the 77 as seen in the right sidebar here: http://monrovia.usembassy.gov/niv_other.html

**Comment by floere** [comment]
Just a note: I always appreciate a PR :)

**Comment by sconstantinides** [comment]
Finally got around to this :) Let me know what you think: #245

**Comment by floere** [comment]
Oh, I merged the associated PR. Closing, thanks all :)
