### ISSUE TITLE
Not validaing a Luxembourg Number

### ISSUE THREAD

**Issue by tbuyle** [floere/phony#218]
Phony.plausible? returns false for the number '352316757' while it seems to be a a valid phone number.

**Comment by floere** [comment]
That is expected – see: https://github.com/floere/phony/blob/master/lib/phony/countries.rb#L559-L566
So a 352 3 <- this is not in Phony yet. What does the 3 refer to?

**Comment by tbuyle** [comment]
According to http://en.wikipedia.org/wiki/Telephone_numbers_in_Luxembourg this number uses the 'old' format (used for number introduced before 2000) with a 2 digits area identifier.

'31' would then be the identifier of Bertrange/Mamer/Munsbach/Strassen

**Comment by floere** [comment]
So Phony is correct in saying it's not valid? (anymore)

**Comment by tbuyle** [comment]
I don't think so.

As I understand it, phone number introduced before 1999 are still valid and use the old format.

The number comes from data I received form a client. I tried calling it and it does work.

**Comment by floere** [comment]
Ok, thanks! Do you feel like updating https://github.com/floere/phony/blob/master/lib/phony/countries.rb#L559-L566?

**Comment by tbuyle** [comment]
Not sure if I can do it but I'll have a look.

**Comment by floere** [comment]
Thank you! :)

**Comment by floere** [comment]
@tbuyle Still up for it?

**Comment by tbuyle** [comment]
I hadn't time to look into this yet :-(

**Comment by floere** [comment]
@tbuyle No problem!

**Comment by floere** [comment]
@tbuyle Still no time?

**Comment by tbuyle** [comment]
Nope. Sorry.

**Comment by floere** [comment]
Ok, thanks! I'll leave it open, then.

**Comment by floere** [comment]
Closing this issue – just reopen it if you need to. Thanks! :dancer:

**Comment by tbuyle** [comment]
It seems that this was solved with #276 - f57a4a4

Great works, thanks !
