### ISSUE TITLE
"999" can no longer be normalized

### ISSUE THREAD

**Issue by baxter** [floere/phony#219]
Hi there, I'm not sure if this is a bug or not. The emergency number '999' seems to behave differently to the emergency number '911' when passed through `normalize`.

```
> ruby -e 'require "./lib/phony"; puts Phony.normalize("911")'
911
> ruby -e 'require "./lib/phony"; puts Phony.normalize("999")'
/Users/baxter/Code/phony/lib/phony.rb:102:in `rescue in normalize!': Phony could not normalize the given number. Is it a phone number? (Phony::NormalizationError)
	from /Users/baxter/Code/phony/lib/phony.rb:100:in `normalize!'
	from /Users/baxter/Code/phony/lib/phony.rb:97:in `normalize'
	from -e:1:in `<main>'
```

Running this through git bisect, it appears that this is the first commit where this fails: 9b4234a5024780f3b781b9a68e9c12104dea9c94

Is this a bug or is it expected behaviour?

Thanks very much,

Paul.

**Comment by floere** [comment]
Phony handles only international numbers. See the README for more info. Cheers!

**Comment by baxter** [comment]
Ok @floere, thanks for your response :)

Just out of interest, does this mean the behaviour for "911" is going to change as well?

**Comment by floere** [comment]
What Phony does if you give it "911" is that it checks first which country it is, and then gives the remaining number to that country to split. 91 is India, so it hands the 1 to India. So a number like 911 is always handled however the country handles it. Cheers!

**Comment by floere** [comment]
That's a "possibly, yes".

**Comment by baxter** [comment]
That makes perfect sense, thanks very much @floere :smile:

**Comment by floere** [comment]
My pleasure :)
