### ISSUE TITLE
Swedish numbers incorrectly returning false for plausible

### ISSUE THREAD

**Issue by ahegyi** [floere/phony#220]
I just noticed that certain Swedish numbers (in Åre) are returning false for `Phony.plausible?`, but I found all of these on the web, which seem to be a good indication of their plausibility.

```ruby
# all returning false, but should return true
Phony.plausible? "+46 647 531 75", cc: "46"
Phony.plausible? "+46 647 200 04"
Phony.plausible? "+46 647 511 40"
```

(See http://www.buustamonsfjallgard.se/ for the first phone number, or [do a search for hotels in Åre](https://www.google.com/maps/search/hotels+near+%C3%85re,+Sweden/@63.3971471,13.0792552,14z/data=!3m1!4b1) for others).

[This line] (https://github.com/floere/phony/blob/master/lib/phony/countries/sweden.rb#L63) seems to be the catch all to allow 5 digit numbers (the NDC for Åre is 647, leaving the subscriber numbers at 5 digits in length), but I am not familiar enough with the DSL to understand if that is indeed true.

How can we allow these and other 5 digit numbers in Sweden? [Wikipedia says they do indeed exist.](http://en.wikipedia.org/wiki/Telephone_numbers_in_Sweden)

**Comment by floere** [comment]
Hi Aron,

That's an interesting case, and thanks for describing it so well.

One idea would be to allow subscriber numbers 5 to 7 digits long (8 digits is Stockholm, i.e. NDC 08 only, and that is handled already before that line), using a regexp.

```ruby
fixed(3) >> split(3,2..4)
```

Checking http://personer.eniro.se/ -> e.g. http://gulasidorna.eniro.se/hitta:test/%C3%A5re, I only found 6 digit subscriber numbers, which are grouped both 3-3 and 2-2-2, which is surprising.

I think the best solution would be to handle the cases with a 3 digit NDC according to length:

```ruby
fixed(3) >>  matched_split(
  /^\d{5}$/ => [3, 2], /^\d{6}$/ => [2, 2, 2], /^\d{7}$/ => [3, 2, 2]
)
```

Would you mind changing this and adding a test case (or three)? That would be fantastic :)

**Comment by ahegyi** [comment]
Hi Florian,

Thanks for the response! I can definitely do this, but when I did some searching around, I found a very descriptive document of Sweden's numbering plan: http://www.pts.se/upload/Ovrigt/Tele/Nummerfragor/Sv_nrplan_telefoni_enl_TU-T_rek_E.164.pdf

Perhaps too much? Not sure. I suppose we could group NDCs into sets of minimum and maximum length, and list the NDCs more discretely (as opposed to having the set `fixed(3)`).

**Comment by floere** [comment]
Hi Aron,

That sounds good – it seems as if most numbers are NDC 3, length 8-9, so that could be the fixed fallback at the end of the rules. Would you mind doing some work on the grouping? (And I can do the rest) We could post the ndc-min-max here, or feel free to fork and we then work on your fork.

**Comment by floere** [comment]
@ahegyi Ping.

**Comment by krukgit** [comment]
I'm not sure if these belong in the same category, but I found a bunch of other false negatives, two of them below:

```
Phony.plausible? '+46770457700'
Phony.plausible? '+4647931830'
```

**Comment by floere** [comment]
@ahegyi @krukgit Any of you like to put some effort into a PR?

**Comment by ahegyi** [comment]
Sorry I've been out of the loop – thanks for the ping @floere, I may have some time next week to dive in!

**Comment by floere** [comment]
@ahegyi Cheers! It's also fine to not have time – just let me know :)

**Comment by floere** [comment]
Closing this issue – just reopen it if you need to. Thanks! :dancer:
