### ISSUE TITLE
Italian N(S)N numbers are sometimes 11 digits

### ISSUE THREAD

**Issue by ahegyi** [floere/phony#221]
It appears that certain Italian National (Subscriber) Numbers can be up to 11 digits, when the first digit in the subscriber number is a `1`. See the excerpt below:

> For geographic numbers, the maximum length is 10 digit except in case the NDC is followed by a
digit equal to 1, where the maximum number length is 11.

_Source_: Page 1 of http://www.itu.int/dms_pub/itu-t/oth/02/02/T020200006B0001PDFE.pdf

Currently, [the maximum limit](https://github.com/floere/phony/blob/master/lib/phony/countries/italy.rb#L112-L119) appears to be 10 digits. Can someone more familiar with the DSL suggest a way to include these? Thanks!

A couple real-world examples:

```ruby
# these should return true, but return false
Phony.plausible? "+39 081 1925 2698", cc: "39" # https://www.facebook.com/pizzeriatrattoriadaciro
Phony.plausible? "+39 081 1920 4667", cc: "39" # http://www.xn--50kal-yta.it/index.php/en/
```

**Comment by floere** [comment]
Hi Aron,

Excellent sleuthing! I implemented a suggestion.

Cheers,
   Florian

**Comment by ahegyi** [comment]
Great! Thanks for the fix. :+1:
