### ISSUE TITLE
Valid Thai numbers return false for plausible?

### ISSUE THREAD

**Issue by krukgit** [floere/phony#225]
It seems Phony doesn't recognize mobile phone numbers in Thailand starting with 9.  Quoting wikipedia - _As codes are being exhausted, a new range, 09x is made available for assignment_. It seems at least 90, 91 and 92 are in use, Phony recognizes only 8x.

**Comment by floere** [comment]
It would be great if you made this into a pull request. Here's where you need to implement the rule: https://github.com/floere/phony/blob/master/lib/phony/countries.rb#L248 and here is where you can add specs: https://github.com/floere/phony/blob/master/spec/lib/phony/countries_spec.rb#L567
Thanks!

**Comment by floere** [comment]
Ping @krukgit

**Comment by gdemonie** [comment]
Hi. phony_plausible doesn't recognize Thai mobile numbers starting with 06, also in use now next to 08 and 09. Very much appreciate if you could change the rule. Thanks!
