### ISSUE TITLE
Danish numbers returns empty string with national format

### ISSUE THREAD

**Issue by vangberg** [floere/phony#227]
With Phony master:

```ruby
Phony.format("4540506070", format: :national) #=> ""
```

Using the following script with `git bisect` lead to the breaking commit: 80c14b904a6aae42c5985ab06499f56aa484c84b

```sh
#/bin/sh

git reset --hard HEAD
bundle
bundle exec ruby -Ilib -rphony -e 'Phony.format("4540506070", format: :national) == "40 50 60 70" ? exit(0) : exit(1)'
result=$?
git reset --hard HEAD
exit $result
```

```
git checkout master
git bisect start
git bisect bad
git bisect good v1.7.4
git bisect run ./find-regression.sh
```

I am not entirely sure how to fix this.

**Comment by floere** [comment]
Meget dårligt! I'll look at it when I get home.

**Comment by floere** [comment]
I've reproduced it.

**Comment by floere** [comment]
Fixed in 2.11.0.

**Comment by floere** [comment]
Thanks for the nice issue entry.

**Comment by vangberg** [comment]
That was quick!

Phony is making my life quite a lot easier.

Thank you.

**Comment by floere** [comment]
My pleasure, and thanks!
