### ISSUE TITLE
US phone number :national format replacement?

### ISSUE THREAD

**Issue by bdmac** [floere/phony#229]
We just updated our Phony gem from 2.2.13 to 2.11.1 to take advantage of some fixes. We also use phony_rails' phony_formatted string helper which pretty much just passes through to Phony. Somewhere between those versions the :national format helper changed (at least for US numbers).

In 2.2.13:
```ruby
"14152223333"..phony_formatted(format: :national, spaces: '-') # => "415-222-3333"
```
but now in 2.11.1:
```ruby
"14152223333"..phony_formatted(format: :national, spaces: '-') # => "1-415-222-3333"
```

On our site we present a form with the country code as a separate drop down to try to better ensure valid phone numbers are collected. I want to be able to show the country code as +1 in the drop down and then "415-222-3333" in the text field next to the country list.

What format parameter can I pass to get that value again? Both :international and :national for US numbers return basically the same value with the exception of the '+' character being included in international but removed from national.

**Comment by bdmac** [comment]
I think I can use something like:
```ruby
Phony.format('14152223333', format: '%{ndc}-%{local}', spaces: '-')
```
but I'm not sure what that will do to international numbers. I looked at the `format_cc_ndc` method but I'm not sure what `trunk` is and how that relates to cc or ndc. Trunk does not appear to be supported if you pass in a format string but gets used in the :national branch of the case statement.

**Comment by floere** [comment]
It did change. The newly appearing "1" is the trunk prefix.
What you could use in the short term is `Phony.split` and use the first element for the drop down, and the rest for the text field.

I'm not sure yet if it would be a good idea to add a `trunk: false` parameter to the format call (it's too late here) – any ideas?

**Comment by bdmac** [comment]
Hard for me to say as I'm not familiar enough with phone numbers in general. Not entirely sure what a trunk prefix is or if all countries have them. 



—

**Comment by floere** [comment]
Your case is special – you need a national number part as if it were just part of a full number, i.e. you don't need the trunk code.

I've added a `trunk: false` option to `format` you can use. It's currently experimental, but I don't expect it to be removed. Just a heads up.

If you have the time, read up on the National Trunk Access code (http://en.wikipedia.org/wiki/Trunk_prefix) – or try calling that number with the 1 in front.
