### ISSUE TITLE
Get full phone number possible with `phony`?

### ISSUE THREAD

**Issue by drowa** [floere/phony#230]
Given two phone numbers, one a full E.164 phone number acting as a source (or as a context), is there a way to transform the other into a full number as well?

For example:

Source: +1-434-222-3333
Target: 223-3334
Result: +1-434-223-3334

Source: +1-434-222-3333
Target: 556-224-3335
Result: +1-556-224-3335

Source: +1-434-222-3333
Target: +1-557-224-3335
Result: +1-557-224-3335

Source: +1-434-222-3333
Target: +55-21-99981-5676
Result: +55-21-99981-5676

Source: +55-11-99981-5677
Target: 99981-5678
Result: +55-11-99981-5678

The idea is to mimic a phone trying to contact another where the source's number is a full E.164 number.

**Comment by floere** [comment]
Hi @drowa,

All your examples look like they could be solved with String replacement:

```ruby
source = "+1-434-222-3333".gsub(/\D/, '')
target = "223-3334".gsub(/\D/, '')

replaced = source[0,source.size-target.size] + target

require 'phony'
p Phony.format(replaced)
```

**Comment by drowa** [comment]
Hi @floere, 

I'm afraid it is not that simple.

Source: +55-21-99981-5676
Target: 1-434-222-3333 (the `+` sign is not required in the target)
Result: +1-434-222-3333

Also, the local numbers of a country/region are not necessarily the same size.

Source: +55-21-99981-5676 (local number has 9 digits)
Target: 2714-0301 (local number has 8 digits)
Result: +55-21-2714-5676

Note the source and the result numbers are E.164 full numbers, while the target is what I would call a dialing number.

I want to convert a dialing number to a E.164 full number, which is, btw, a particular case of a dialing number.

Source: +55-21-99981-5676
Target: +1-434-222-3333 (E.164 full number)
Result: +1-434-222-3333

For example, in a cell phone, the majority of the numbers in a contact list are not E.164 numbers (they are all dialing numbers though). In my mobile app, given the cell phone E.164 full number, I would like to convert all numbers in the contact list to E.164 full numbers; like a normalization process.

I'm not even considering special dialing numbers like 911.

Source: +1-434-222-3333
Target: 911
Result: <error> (I don't think 911 has a E.164 representation)

**Comment by floere** [comment]
Do you know the level of the target number? (int'l, national, local) If you do, `Phony.split` could be what you are looking for.

In any case, Phony only works with full E164 numbers. Anything regarding numbers that do not conform cannot be handled by Phony.

**Comment by floere** [comment]
If you know what level the target number is, you can replace the appropriate parts in the `split` source.

See:

```ruby
require 'phony'

source = Phony.split(Phony.normalize("+1-434-222-3333"))
target = "223-3334"

p [source, target]

cc, ndc, *rest = source

replaced = [cc, ndc, target].join('-')

p replaced
```

**Comment by drowa** [comment]
Perhaps we could try all levels until we find a plausible target, starting from int'l then national and finally local.

**Comment by drowa** [comment]
Or the contrary, starting from local then national and finally int'l.

**Comment by floere** [comment]
I thought of that too, but there's the issue that e.g. a ndc+local number could well be plausible just attached as a local number in some countries (Germany comes to mind).

**Comment by floere** [comment]
As usual with phone numbers, my impression is that this needs to be solved in the UI, perhaps trying to give good suggestions to support the user.

**Comment by drowa** [comment]
I suspect the E164 full number of the source should be enough to infer the E164 full number of the target, assuming the target has such number (i.e. there is no international number for 911 in US).

Perhaps we could do that using [trunk codes](http://en.wikipedia.org/wiki/Trunk_prefix) and area codes. Note the `+` signal in a E164 number is just a place holder for the appropriate [international call prefix](http://en.wikipedia.org/wiki/List_of_international_call_prefixes) which is a trunk code.

For example, let the source be `+1-434-222-3333` and the target be `011-55-21-99981-5676` (dialing number). The target can be translate to `+55-21-99981-5676` (E164 number) because `011` is the trunk code used in US (`+1`) to select an international telephone.

Of course we would need to know the [telephone numbering plan](http://en.wikipedia.org/wiki/Telephone_numbering_plan) of the source to know area codes and special numbers (e.g. 911 in US).

For example, let the source be `5521999815676` (sources don't need to be formatted) and the target be `27140301` (targets don't need to be formatted either). To translate the target we would "select" [the Brazilian telephone numbering plan](http://en.wikipedia.org/wiki/Telephone_numbers_in_Brazil) (`+55`) realizing that the source is a 9 digit cell phone from Rio de Janeiro (`21`), while the target could represent a 8 digit wired local (Rio) phone number. With that information we could translate the target to `+55-21-2714-0301`.

I know this looks out of the scope of Phony, but looking into its source code it seems all necessary information for this kind of translation is there. That's why I posted this question.

I suspect applications like Viber and WhatsUp perform this kind of translation when they scan our contact list (targets). Note their "registration" requires all users to enter the E164 full number of our devices (source), mostly because, for security reasons, they cannot get this number directly. The translation allows those applications to connect users in batch (kind of a greed method).

**Comment by floere** [comment]
@drowa If you don't know the target's level (full, ndc+local, or just local), then you cannot be 100% sure of whether you put together the right number. If you are happy with 90-95% accuracy, then I think you should give your idea a go.
Other than that, this is not about Phony anymore, so I am closing the issue.
