### ISSUE TITLE
Cannot validate certain US numbers

### ISSUE THREAD

**Issue by wikyd** [floere/phony#232]
I noticed an issue with v2.12.1 where my US phone number is no longer plausible!  Downgrading to v.2.12.0 resolved the issue for me. The number that failed has an area code of 217.  Other US numbers seem to work.

**Comment by floere** [comment]
This was introduced in #231 (ping @nbrookie).

Checking this map: http://www.nanpa.com/area_code_maps/display.html?cainset2 tells me that in CA 2XXs exist.

I've loosened the restriction and removed 2XX numbers in 2.12.2 – we can work on refinements later.

**Comment by nbrookie** [comment]
@wikyd @floere Good catch. Looks like I misread the NANPA rules. According to this line, the `2` should definitely be included as valid:

`The format of an area code is NXX, where N is any digit 2 through 9 and X is any digit 0 through 9`

Sorry about that!

**Comment by floere** [comment]
@nbrookie No problem at all, thanks for the explanation :)

**Comment by wikyd** [comment]
@floere @nbrookie thanks!
