### ISSUE TITLE
Valid UK number flagged as invalid

### ISSUE THREAD

**Issue by weppos** [floere/phony#233]
http://checkwhocalled.co.uk/phone-number/01604704451

```
2.1.5 :003 > Phony.plausible?('+44 01604704451')
 => false
```

The same applies to `+44 07771 5862xx`.

**Comment by floere** [comment]
@weppos Do you have time for a PR?

**Comment by floere** [comment]
Closing this issue – just reopen it if you need to. Thanks! :dancer:
