### ISSUE TITLE
Normalize trunk code handling throughout the gem

### ISSUE THREAD

**Issue by ardecvz** [floere/phony#240]
Hello, Florian!
I'd like to confirm before opening an pull request how [trunk code] (https://en.wikipedia.org/wiki/Trunk_prefix) handling should work throughout the gem in your opinion. Right now, it seems a little bit controversial across different countries.

For example, my potential customer sent me a random E164-conform russian number:
`+7 123 456 78 90`.
You could mentally parse it like this:

Int call prefix | Country code | National Destination Code | Subscriber code
--- | --- | --- | ---
+ | 7 | 123 | 456 78 90

You'll be unable to get in trouble with this number: `Phony.plausible? '+7 123 456 78 90' == true && Phony.normalize '+7 123 456 78 90' == '71234567890'`. And if I show the number to my customer support in another country, they will certainly call him by replacing `+` sign with the local specific international exit code (common 00 or 011 in USA, etc.).

However, my another not-so-smart client doesn't know that the Internet is global and he should use international numbers. He's working with local site (maybe buying pizza?) so he sent me nationally formatted number:
`8 123 456 78 90`.

Obviously, it works for him and doesn't work for Phony. But I could easily fix it by adding country since I know where my client lives:
`+7 8 123 456 78 90`.
And parsed:

Int call prefix | Country code | Local trunk code | National Destination Code | Subscriber code
--- | --- | --- | --- | ---
+ | 7 | 8 | 123 | 456 78 90

And... here be dragons:

1) Phony treats trunk codes with and without parentheses differently - it entirely [strips a parenthesed trunk code](https://github.com/floere/phony/blob/v2.12.6/lib/phony/country_codes.rb#L33) but [parses a simple one](https://github.com/floere/phony/blob/v2.12.6/lib/phony/country.rb#L81). In my opinion, we shouldn't rely on formatting and process them identically.

2) It's excepted that after normalization there'll be E164 phone number (without trunk code) but we don't remove it for Russia, Hungary, Lithuania in error (`Phony.normalize '+7 8 123 456 78 90' == '781234567890' # and it's wrong`).
It seems it's caused by a mistaken implementation of #172 - @andrius means that we must always normalize trunk code but beware that NDC may start with 8 (it's crazy but in Russia 8 is a trunk code and also it may be in NDC so we can't just `gsub` 8 from start of the number).

Moreover, I think `trunk('0', normalize: false)` DSL should be used only for Italy which always includes trunk codes as other countries either use local-only trunk codes or don't use them at all (like Spain mentioned in #172).

3) According to [Wikiepedia](https://en.wikipedia.org/wiki/Trunk_prefix#Countries_no_longer_using_a_national_trunk_prefix), we also wrongly add trunk code to Latvia.

4) The most confusing thing are new Japanese codes introduced in #239. They include leading 0 which, I believe, is a trunk code. According to E164 docs, there's a strong recommendation to not use leading zeros in NDC and it seems they're included mistakenly as NDC is usually presented with leading zero in Wikipedia (for example, [Germany's](https://en.wikipedia.org/wiki/Telephone_numbers_in_Germany) page).

5) I'm also interested which the best way of trunk code handling in your opinion? For example, `Phony.plausible?` returns `false` in #233 only because of included trunk codes. Right now, it depends on the country provider and I strongly suggest that it should be standardized.
E164 doesn't allow trunk codes in notation (and parentheses) but developers may want them as it greatly simplifies the usage of national numbers. As described in my use case, it should be a widespread problem.

I'm sorry for a huge writing, I'm chatty today ;) By the way, big thanks for your great gem!

**Comment by floere** [comment]
Hi Artur,

From a quick read, you're making some good points.
Please give me some time to parse all of it in peace and formulate some answers.

Respond to you soon!

**Comment by ardecvz** [comment]
@floere,
I'd like to recommend to you a new indispensable free tool introduced recently by [Twilio](https://www.twilio.com/lookup) on the chance that you haven't seen it already.

It mirrors Phony's functionality with the exception of network-burden and closed-source way. However, you could use it to check yourself while you're working with some questionable foreign numbers. Perhaps it may be incorporated into the gem's test suit as an additional verification.

For example, it confirms my doubts with #239 as it really includes trunks.

Right now, I'm also interested in one more thing:
6) To properly parse trunk codes we have to delimitate them from area codes. It's easy for the majority of countries (as their NDC doesn't start with 0 usually) except ex-USSR ones. Normalizing the latter requires either:
- a new DSL `total_length` or something like that which indicates total number of digits in the country's numbers. It would reliably solve the trunk problem for Russia and friends as these numbers always contains 11 digits in the E164 form so any length exceeding this threshold shows trunk code including. Although it seems like a good solution, I'm worried that other countries may not use fixed length.
- rely on the already presented in the gem NDCs but I'm not sure how complete they are. Maybe you may give me a better insight into their completeness.

**Comment by floere** [comment]
Hi @ardecvz,

On a general note, Phony has been developed very organically, and it works well that way. That is – the code may be funky in places, but as long as the specs all pass (1149 of them), then I am happy. But nonetheless, if you find a spot where it's too funky, I am very interested to rewrite it, especially if it can be made simpler and code removed.

1) What is your proposal, specifically?

2) I'm starting to see your point. The trunk code should be removed in a country-specific manner.

3) Always open to PRs :) I can't do it all on my own. What I can is manage the project, implement the core, and perhaps write a country specification here and there.

4) I've reverted that PR. I pulled it since I misremembered the Japanese system being similar to the Italian case, so it made sense at the time.

5) I'm starting to think that this could be handled by moving cleaning (or rather, trunk removing) towards being country-specific.

Do you have a suggestion what to do in cases where the trunk is equal to an NDC?

**Comment by floere** [comment]
I'm closing this as nothing is happening. Please reopen oder open a new issue in case anybody wants this to continue.
