### ISSUE TITLE
Incorrect extra leading 0 in Italian numbers

### ISSUE THREAD

**Issue by tristanjahier** [floere/phony#241]
It seems there is a problem with Italian numbers.
I'm not Italian myself, but I have 2 Italian clients which reported me that some numbers were wrongly formatted. For example:
* mobile : `333 333 76 47` => `0333 333 7647`
* landline : `0108480161` => `0010 8480161`

As you can see, an extra zero is put at the beginning of the phone number.

But if you use the `format: :international` option, it gives a valid international number, without an extra zero:
* `333 333 76 47` => `+393333337647`
* `0108480161` => `+390108480161`

[**Twilio lookup**](https://www.twilio.com/lookup) service seems to confirm this issue.

Any idea about that?

**Comment by floere** [comment]
Thanks! The 0 came from a format before 1999. This is now corrected in 2.12.8.

**Comment by tristanjahier** [comment]
Thanks! That seems to work well. ;-)
