### ISSUE TITLE
Phony.plausible?('+41 (044) 364 35 33') returning false

### ISSUE THREAD

**Issue by brentahiti** [floere/phony#242]
Everything is in the title.
In the case of your last example on your README in the normalizing section, the number isn't plausible. Seems like to be the case with other Swiss numbers like '+41 (021) 560 02 02' or '+41 (024) 496 61 61' (although '+41 21 560 02 02' and '+41 24 496 61 61' are plausible) which I found here : http://yellow.local.ch/en/q?what=Private+school&where=&rid=2kPq

**Comment by floere** [comment]
I've fixed this. The numbers you found are not in their international format, where correctly the 0 is not added. So they don't work as an example. I did it nonetheless, because it makes sense to remove a zero after a ( in all cases so far. Cheers!
