### ISSUE TITLE
Real Austrian number not plausible? 

### ISSUE THREAD

**Issue by sime** [floere/phony#246]
The follow number is returned as not plausible: +43 3115 3307

```
irb(main):005:0> require 'phony'
=> true
irb(main):006:0> Phony.plausible?('+43 3115 3307')
=> false
```

Even though it is publicly advertised: http://brassino.at/  (in the footer)

This may be an invalid comparison, but Phonelib seems to be okay with it:
```
irb(main):001:0> require 'phonelib'
=> true
irb(main):002:0> Phonelib.parse('+43 3115 3307').type
=> :fixed_line
```

**Comment by floere** [comment]
I've added a spec and have expanded Austrian numbers with a 4 digit NDC to have a length of 7 to 13. Released in 2.12.12. Thanks for the pointers and the PR! :)
