### ISSUE TITLE
Czech false positive on +420123456789

### ISSUE THREAD

**Issue by sime** [floere/phony#249]
Hello,

I believe that the following number is a false positive: +420123456789

irb(main):015:0> Phony.plausible?('+420123456789')
=> true
irb(main):016:0> Phonelib.parse('+420123456789').type
=> nil

**Comment by floere** [comment]
You are right. I tried to call it for fun.

The Czech numbers are basically not defined yet beyond a very general definition.

**Comment by sime** [comment]
I had friend do a little Czech Googling.

http://www.predvolby.info/predvolby-mobilnich-operatoru.html
http://www.predvolby.info/telefonni-predvolby-mest.html

Though these details are pretty much exactly match what is already on the Wikipedia page for Telephone number in the Czech Republic.

**Comment by floere** [comment]
Would you mind trying your hand at an improvement of the rules and a PR?

**Comment by floere** [comment]
Closing this issue – just reopen it if you need to. Thanks! :dancer:
