### ISSUE TITLE
Normalizing number such 5302763344 removes 0 from prefix

### ISSUE THREAD

**Issue by lfavaro-daitan** [floere/phony#258]
Normalizing number such 5302763344 removes 0 from prefix giving you 532763344

**Comment by floere** [comment]
Hi Luciano,




Thanks for the issue. Can you describe what you expected, what happened instead, and why you think it ahould work as you expected?




Cheers,

   Florian

**Comment by lfavaro-daitan** [comment]
Hey Florian, thanks for the quick response [😊]

Based on the examples:
Phony.normalize('41443643533').assert            == '41443643533'
Phony.normalize('+41 44 364 35 33').assert       == '41443643533'
Phony.normalize('+41 44 364 35 33').assert       == '41443643533'
Phony.normalize('+41 800 11 22 33').assert       == '41800112233'
Phony.normalize('John: +41 44 364 35 33').assert == '41443643533'
Phony.normalize('1 (703) 451-5115').assert       == '17034515115'
Phony.normalize('1-888-407-4747').assert         == '18884074747'
Phony.normalize('1.906.387.1698').assert         == '19063871698'
Phony.normalize('+41 (044) 364 35 33').assert    == '41443643533'


I would expected that this should work:


Phony.normalize('530 298 7666').assert       == '5302987666'


but this assert fails.


The prefix 530 is from California.


If I add +1 to the number, it works fine:


Phony.normalize('+1 530 298 7666').assert       == '15302987666'


This assert pass.


Regards,

Luciano

________________________________
De: Florian R. Hanke <notifications@github.com>
Enviado: sexta-feira, 12 de junho de 2015 14:40
Para: floere/phony
Cc: Luciano Favaro
Assunto: Re: [phony] Normalizing number such 5302763344 removes 0 from prefix (#258)

Hi Luciano,




Thanks for the issue. Can you describe what you expected, what happened instead, and why you think it ahould work as you expected?




Cheers,

   Florian

**Comment by floere** [comment]
Oi Luciano,




Phony needs international numbers to work. See the README.




If you only do US numbers, you could do: us = Phony['1']; us.normalize('...')




Cheers,

   Florian

**Comment by lfavaro-daitan** [comment]
Haa OK...


Got it.


Thanks Florian!

Luciano

________________________________
De: Florian R. Hanke <notifications@github.com>
Enviado: sábado, 13 de junho de 2015 10:55
Para: floere/phony
Cc: Luciano Favaro
Assunto: Re: [phony] Normalizing number such 5302763344 removes 0 from prefix (#258)

Oi Luciano,




Phony needs international numbers to work. See the README.




If you only do US numbers, you could do: us = Phony['1']; us.normalize('...')




Cheers,

   Florian

On Fri, Jun 12, 2015 at 7:50 PM, Luciano Fávaro <notifications@github.com>
wrote:

> Hey Florian, thanks for the quick response [??]
> Based on the examples:
> Phony.normalize('41443643533').assert == '41443643533'
> Phony.normalize('+41 44 364 35 33').assert == '41443643533'
> Phony.normalize('+41 44 364 35 33').assert == '41443643533'
> Phony.normalize('+41 800 11 22 33').assert == '41800112233'
> Phony.normalize('John: +41 44 364 35 33').assert == '41443643533'
> Phony.normalize('1 (703) 451-5115').assert == '17034515115'
> Phony.normalize('1-888-407-4747').assert == '18884074747'
> Phony.normalize('1.906.387.1698').assert == '19063871698'
> Phony.normalize('+41 (044) 364 35 33').assert == '41443643533'
> I would expected that this should work:
> Phony.normalize('530 298 7666').assert == '5302987666'
> but this assert fails.
> The prefix 530 is from California.
> If I add +1 to the number, it works fine:
> Phony.normalize('+1 530 298 7666').assert == '15302987666'
> This assert pass.
> Regards,
> Luciano
> ________________________________
> De: Florian R. Hanke <notifications@github.com>
> Enviado: sexta-feira, 12 de junho de 2015 14:40
> Para: floere/phony
> Cc: Luciano Favaro
> Assunto: Re: [phony] Normalizing number such 5302763344 removes 0 from prefix (#258)
> Hi Luciano,
> Thanks for the issue. Can you describe what you expected, what happened instead, and why you think it ahould work as you expected?
> Cheers,
> Florian
> On Fri, Jun 12, 2015 at 7:30 PM, Luciano Fávaro <notifications@github.com>
> wrote:
>> Normalizing number such 5302763344 removes 0 from prefix giving you 532763344
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/floere/phony/issues/258
> -
> Reply to this email directly or view it on GitHub<https://github.com/floere/phony/issues/258#issuecomment-111570415>.
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/floere/phony/issues/258#issuecomment-111573187

-

**Comment by floere** [comment]
Great! 👍
