### ISSUE TITLE
Split adds 'false' in the middle of the array

### ISSUE THREAD

**Issue by allavena** [floere/phony#259]
Phony.split('4234760987')
 => ["423", false, "476", "09", "87"]. 

I don't think there should be a false in there, should there? 
According to Wikipedia, this a normalised Lichtenstein phone number, (dialed internationally as +423 xxx xx xx)

Thanks
André

**Comment by floere** [comment]
Hi André,

In the current version of Phony, this is expected. You want to know if a country has an NDC or not – Liechtenstein does not.
See also e.g. Denmark, https://github.com/floere/phony/blob/master/spec/lib/phony/countries_spec.rb#L180-L182.

Cheers,
   Florian

**Comment by floere** [comment]
Thanks to you I've added a note to the README (see referencing commit above). Cheers!
