### ISSUE TITLE
UK 0203 numbers not handled correctly

### ISSUE THREAD

**Issue by Carpela** [floere/phony#261]
0203 numbers (London, UK) seem to not be recognised as UK numbers

    [13] pry(main)> PhonyRails.normalize_number('02031234567', default_country_code:'GB', add_plus:false)
    => "2031234567"
0207 numbers are handled correctly.

    [14] pry(main)> PhonyRails.normalize_number('02071234567', default_country_code:'GB', add_plus:false)
    => "442071234567"
With country code this works fine.

    [15] pry(main)> PhonyRails.normalize_number('02031234567', country_code:'GB', add_plus:false)
=> "442031234567"

The issue appears to be the following:

    [24] pry(main)> Phony.plausible?('02031234567')
    => true
    [25] pry(main)> Phony.plausible?('02071234567')
    => false
    [22] pry(main)> PhonyRails.country_code_from_number('02031234567')
    => "20"
    [23] pry(main)> PhonyRails.country_code_from_number('02071234567')
    => nil
Not sure how to stop Phony thinking that an 0203 number is from Egypt...?

**Comment by Carpela** [comment]
Apologies, asked the chap from PhonyRails who suggested I throw it your way.

**Comment by floere** [comment]
@Carpela I don't have much time, so: would you mind reading the very first line of Phony's README? Also, consider how Phony should know how to handle a number if i does not know which country it is from.

**Comment by floere** [comment]
@Carpela Apologies for the first response – I was mistaken. This does seem like a PhonyRails issue, because it's PhonyRails' decision to not return a country code if a number does not seem to be plausible. If it would return the presumed country code, then it would be no issue.

**Comment by floere** [comment]
@Carpela In fact, looking more into it – I do believe PhonyRails's process may be slightly incorrect. 

Using vanilla Phony, we can see that if you add the CC for the UK, normalize, and check for plausibility:

```ruby
$ ruby -e 'require "phony"; p Phony.plausible?(Phony.normalize("4402031234567"))'
true
$ ruby -e 'require "phony"; p Phony.plausible?(Phony.normalize("4402071234567"))'
true
```

**Comment by floere** [comment]
It may be a good idea to pull the PhonyRails maintainer in here.

@joost I like your default country code idea. I am wondering what is going wrong here – when I add the CC, then normalize, then check for plausibility, both numbers return true. What process are you using to either add the CC or not?

**Comment by floere** [comment]
@Carpela @joost Any updates?

**Comment by joost** [comment]
Will try to find some spare minutes tomorrow to have a look :)

**Comment by floere** [comment]
Closing this issue – just reopen it if you need to. Thanks! :dancer:

**Comment by Carpela** [comment]
This one's still a bit of an annoying issue. 

https://github.com/joost/phony_rails/issues/95

It seems to be falling somewhere in the gap. 
phony is (possibly correctly) saying this is a plausible egyptian number. Unfortunately it's also a plausible UK number.... 
phony_rails when trying to use the GB country code is checking if it's a foreign number first, whcih isn't a terrible idea, but in this case is turning things egyptian rather than respecting the default country code.

Not sure where to apply any change. It does seem to just be with 0203 numbers. (Which are quite a populate london number for businesses.

**Comment by floere** [comment]
I don't have any more information than I had when I wrote https://github.com/floere/phony/issues/261#issuecomment-113632812.

**Comment by Carpela** [comment]
Ok. I could try something but I'd likely break it.... :) 
It's a weird edge case, I guess. But somewhere in that gap it would be great if we could fix it. 
I'm doing the following currently

def check_invalid_numbers
    if self.phone =~ /^(203|0203)/
      # this first clause picks up the UK numbers
     if self.phone[0..3] == "0203"
        self.phone[0..3] == "44203"
    # This would bugger up egyptian numbers, I just don't happen to have any
      elsif self.phone[0..2] == "203"
        self.phone[0..2] == "44203"
      end
    end
  end

**Comment by floere** [comment]
@Carpela I think it's great you found a solution and are making Phony work for you (or in this case, PhonyRails)! Unfortunately, I can't change Phony as it works as advertised (it can't do magic).

**Comment by joost** [comment]
Just had a minute to look into this. Please check joost/phony_rails#95 for a fix.

**Comment by floere** [comment]
@joost Cheers 😊
