### ISSUE TITLE
Normalization does not work properly

### ISSUE THREAD

**Issue by galulex** [floere/phony#274]
`Phony.normalize('38 (063) 608-6021')` => `38636086021`

Zero is missing

`Phony.normalize('38 (163) 608-6021')` => `381636086021`

Valid

**Comment by floere** [comment]
:dancers:

**Comment by galulex** [comment]
:smiling_imp:

**Comment by floere** [comment]
:8ball: -> Reply hazy, try again.

**Comment by galulex** [comment]
The Phony should keep the zero.

[Docs](https://github.com/floere/phony/blob/master/qed/normalize.md#special-cases)

Does not normalize a correct 0 away.

**Comment by floere** [comment]
Soo - this issue is now open and serious again? (Just checking since you closed it initially)

**Comment by galulex** [comment]
The issue is active

**Comment by floere** [comment]
Ok, thanks :) The documentation in Phony is also half of its specs, so the docs actually are run and checked before each release.

So you expect a country code `38` number (?) to not normalize the `0` away, based on `Does not normalize a correct 0 away.` on a `39` country code (Italy)?

**Comment by galulex** [comment]
I am expected `Phony.normalize('38 (063) 608-6021')` to return `380636086021`

currently it returns `38636086021`

**Comment by floere** [comment]
What country is `38`? Wasn't that Yugoslavia?

Whether to remove a `0` or not is country dependent.

**Comment by galulex** [comment]
Sorry my fault. Should be `380`. Sorry again

**Comment by floere** [comment]
@galulex Ohhhh, got it. No worries! Enjoy Phony :)
