### ISSUE TITLE
Belarus phone number normalization issue

### ISSUE THREAD

**Issue by SergeyKishenin** [floere/phony#277]
Local numbers like `8033xxxxxxx`, (with `0` previous to code described in https://github.com/floere/phony/blob/master/lib/phony/countries/belarus.rb#L113) are normalized to `+375033xxxxxxx`.

But expected result is `+37533xxxxxxx` (without `0`)

How it can be achieved? Thanks!

**Comment by floere** [comment]
Is this about the following?

> When calling within Belarus add 0 to the trunk prefix. This way dialing within the country is practically unchanged. In 2003 the abbreviated dialing within areas was replaced with a full 9-digit number + 2-digit trunk prefix. Previously it was possible to dial 82RRnn-nnn to reach a number in the same area. Now it is required to dial 80-AARRnn-nnn where AA is the area code

**Comment by SergeyKishenin** [comment]
Seems like yes

**Comment by floere** [comment]
Does this cover your test case? https://github.com/floere/phony/commit/ed5d7f113ef37e6a7364e9b8d12bce3737673af8

**Comment by SergeyKishenin** [comment]
Yes! That was so easy actually. :+1:

**Comment by floere** [comment]
Released in 2.15.0 – I've also added formatting with the `national` option. Cheers! :rocket:

**Comment by SergeyKishenin** [comment]
Awesome, thanks!
