### ISSUE TITLE
False negative for Bosnia and Herzegovina

### ISSUE THREAD

**Issue by bejar37** [floere/phony#284]
Hi, Bosnian mobile numbers without a trunk code (zero) are being rejected. If you look at the [Wikipedia article].

(https://en.wikipedia.org/wiki/Telephone_numbers_in_Bosnia_and_Herzegovina#Mobile_phone_codes), Bosnian mobile numbers are valid with or without a trunk code. [Twilio](https://www.twilio.com/lookup) agrees, and says that the actual phone number value is the same with or without the leading zero. This is a problem for me because my client-side phone number formatting library is stripping leading zero digits.

I was trying to figure out how to make the trunk code optional in the DSL, but I wasn't quite sure how.

Thanks! This library has been awesome (been using it in production for 9~ months now).

**Comment by floere** [comment]
Hi Miguel! Thanks for the issue :rocket: – do you have a few confirmed failing examples to help me? Btw, the solution is probably to make trunk be `0?`, see Belarus for a similar example.

**Comment by bejar37** [comment]
Thanks for the quick reply @floere!

An example number is `38761899941`, which is not plausible, vs `387061899941`, which is plausible. Twilio lookup shows that both numbers are valid, and returns the same `phone_number` field for both of them (without the 0 trunk).

Changing the trunk code to `0?` isn't solving the situation, Phony is running into an issue matching the correct code and fails on a national number length validation.

-Miguel

**Comment by floere** [comment]
Thanks! Changing the trunk code is probably solving one issue. The other issue is lengths – and currently, the rules are extremely simple: `country '387', trunk('0') | fixed(2) >> split(3,2,2)` – as an example, if the last digit group can be longer, then we'd have to change the rule to `country '387', trunk('0') | fixed(2) >> split(3,2,2..4)`. Does that help? Looking at the Wiki page, it seems as if it mostly needs to be `country '387', trunk('0?') | fixed(2) >> split(3,3)`.

**Comment by bejar37** [comment]
OK, I ended up changing the behavior in my client library rather than here. I'm still not quite sure if Bosnian mobile numbers should always be "061" or not. Feel free to close this issue if you think that no work needs to be done on the phony side.

**Comment by floere** [comment]
Work probably does need to be done, but I am not sure yet what. So I'll leave it open if you don't mind. Glad you found a solution! :)

**Comment by floere** [comment]
Currently closing until it is brought up again. Thanks again! :rocket:
