### ISSUE TITLE
Phony plausible return false for thai mobile phone numbers starting with 06

### ISSUE THREAD

**Issue by gdemonie** [floere/phony#286]
Hi. phony_plausible doesn't recognize Thai mobile numbers starting with 06, also in use now next to 08 and 09. Very much appreciate if you could change the rule. Thanks!

**Comment by floere** [comment]
@gdemonie Hi Guillaume! Can you maybe point me to an official document with that info? Thanks!

**Comment by gdemonie** [comment]
http://help.mobiletopup.com/knowledge-base/what-is-the-format-of-a-thai-mobile-number/

**Comment by gdemonie** [comment]
My own number starts with 06 but that's the most official resource I could find in English. Thanks!

**Comment by floere** [comment]
Thanks! 😊
This also helped: https://en.wikipedia.org/wiki/Telephone_numbers_in_Thailand#Mobile_phone_codes_and_IP_telephony
Updated and released in 2.15.4 :rocket:

**Comment by gdemonie** [comment]
Great, thanks!
