### ISSUE TITLE
French formatting

### ISSUE THREAD

**Issue by Apokly** [floere/phony#294]
Hi

I have a bug with french formatting :

```ruby
"06-12-34-56-78".phony_normalized(default_country_code: 'FR') # gives me "+33612345678", good
```

but
```ruby
"06-87-73-83-58".phony_normalized(default_country_code: 'FR') # gives me "+687738358", wrong
```

The only difference is the phone number. The default formatting is the same
Is there a bug or is it my bad ?

Thank you.

**Comment by Apokly** [comment]
Same for "06-24-24-02-48", "04-68-50-11-99"

**Comment by floere** [comment]
@Apokly Hi Fabien! I can't give support for non-Phony related functionality. Cheers! :rocket:
