### ISSUE TITLE
Can  I use this gem for landline numbers?

### ISSUE THREAD

**Issue by Hirurg103** [floere/phony#297]
We have landline numbers in our system. And we want to use phony to normalize/format/validate them.
Can we use phony for this purpose?

For example, if I format 020 7888 2808 Phony will convert it to +20 78 882808.
As I know there is no "+" button in landline telephone set

**Comment by floere** [comment]
Sure!

```ruby
ruby -e 'require "phony"; p Phony.format(Phony.normalize("020 7888 2808"), :format => :international_relative)' # => "0020 78 882808"
```

Also see the docs: https://github.com/floere/phony/blob/master/qed/format.md

Have fun! :rocket:

**Comment by Hirurg103** [comment]
this input number is 020, its international equivalent is 0044 20

**Comment by floere** [comment]
Can you, in code, explain what you expect Phony to do, please?
