### ISSUE TITLE
False negatives for valid US numbers

### ISSUE THREAD

**Issue by peterkeen** [floere/phony#303]
I'm seeing false negatives for valid US numbers. I know they're valid because when the customer formats them in international style, Phony says they're plausible.

```
601-668-xxxx
503-436-xxxx
```

I'd love to help patch this. Could I get a pointer on where to start looking?

**Comment by peterkeen** [comment]
Nevermind. I see what the problem is (I need to use PhonyRails to get the US default translation working). Thanks for the great library!

**Comment by floere** [comment]
Glad to hear it :)
