### ISSUE TITLE
Normalize always prepending CC for UK numbers

### ISSUE THREAD

**Issue by clowder** [floere/phony#304]
I have an issue where calling `#normalize` with a UK number and CC will always prepend the CC – regardless of whether it's present or not. Failing test cases can be found here https://github.com/floere/phony/compare/master...clowder:cc-adding-infinitely.

It feels like the correct behaviour would be to just add it's missing – as far as I can tell this is how the US currently works.

Thanks in advance for your time and for maintaining such a useful library.

**Comment by floere** [comment]
Hi @clowder!
Thanks for entering the issue and your kind words.
I'm wondering what your use case is – what are you using `#normalize` for?

**Comment by clowder** [comment]
Currently we using it to normalise user input on a form — normalising all numbers to their international form. 
In out specific case we also know the address of the user, so we can pass the CC into Phoney. 






On Tue, Jan 19, 2016 at 1:41 AM -0800, "Florian R. Hanke" <notifications@github.com> wrote:












Hi @clowder!

Thanks for entering the issue and your kind words.

I'm wondering what your use case is – what are you using #normalize for?

**Comment by floere** [comment]
Hi Chris

Sadly, normalize can't be used for this purpose for all countries – for NANP (e.g. the US) it works, but in most cases, Phony cannot know whether it already was given the full number (including CC) or not.

The current normalize method with `cc` option is only useful if you have a non-CC number of a country to which Phony can prepend the CC. You are essentially telling Phony "I have a partial number here, so you can't figure out where it is from, but I know which country it is, so just prepend this country code".

If you only passed in non-CC numbers then your method should work.

I hope that helps!

**Comment by clowder** [comment]
Understood, thanks!
