### ISSUE TITLE
Swedish numbers with trunk prefix

### ISSUE THREAD

**Issue by fespinoza** [floere/phony#305]
Phony doesn’t recognize the valid phone number `+460736829291`
because of the extra 0 in the `+46` prefix.

So

```ruby
Phony.plausible?(+46073682929) # false
Phony.plausible?(+4673682929) # true, now it's "+46" prefix not "+460"
```

Also

```ruby
Phony.normalize(+46073682929) # => +4673682929
```

both phone numbers should be valid

i found the issue https://github.com/floere/phony/issues/184, where dutch numbers are being normalized
https://github.com/floere/phony/blob/master/lib/phony/countries/netherlands.rb#L58 but swedish numbers aren't https://github.com/floere/phony/blob/master/lib/phony/countries/sweden.rb#L60

Is this the intended behavior? otherwise I can do a PR for the patch :)

**Comment by floere** [comment]
Hi Felipe!

Re #184: To remove the trunk code when normalizing is default – so the behavior for the Netherlands and Sweden is the same, just explicit for the Netherlands. (Thanks for looking that up, btw!)

It's not normally the case that a trunk code is used when calling from outside a country using the CC, so I am wondering why you think that both phone numbers should be valid. Do you have any evidence to support that?

Thanks for the nice issue entry so far! :+1: :rocket:

**Comment by floere** [comment]
Closing. Please reopen if you have new info 😊
