### ISSUE TITLE
Are US extension-followed supported? Seems to be common thing to have.

### ISSUE THREAD

**Issue by vittorius** [floere/phony#306]
Hey,

was browsing through a bunch of phone number validation libraries but stopped at yours because it looks  the most actively developed, mature and easy to use. Well done :+1: 

But, unfortunately, I haven't found the support for US business numbers with extensions (like "1-258-955-9931 x59734" or "1-258-955-9931 ext. 59734", both are important to support for me). It seems to me (from reading issues of this repo) that for some of European countries you do support extensions.

Can you give me any useful info on enabling the support of such numbers to be plausible? (Now, they are marked as non-plausible).

**Comment by floere** [comment]
Hi @vittorius!

It may be a common thing to have, but as the summary states in the first word, it's a library for handling E164 numbers (in Phony's case with leniency wherever feasible). I would suggest you write a small wrapper method for Phony that removes clearly marked extensions before checking for validity (and possibly releasing it as a gem).

Cheers! 🙂
   Florian

**Comment by vittorius** [comment]
I see. Yes, I've read the disclaimer... OK, thanks for a kind response anyway )

**Comment by floere** [comment]
Sure! It should not be hard to extend, assuming `x` or `ext.` are always used on extensions 😊

```ruby
def plausible_with_extensions? number, hints = {}
  ext_removed = number.sub(/\s?(?:ext|x).+$/, '')
  Phony.plausible?(ext_removed, hints)
end
```
