### ISSUE TITLE
Local numbers sometimes plausible

### ISSUE THREAD

**Issue by odedniv** [floere/phony#307]
```ruby
Phony.plausible?("0508000000")
=> true
# oh good so we can format this?
Phony.format("0508000000")
# => NoMethodError: private method `format' called for 1:Fixnum
# nope
```

`Phony::CountryCode` cleans the number before checking which removes the leading "0", and I guess 508 is a valid country code. Should there be a special case for leading 0?

**Comment by floere** [comment]
Hi @odedniv 

Plausible works on non-normalized, but normalizable E164 numbers, and format _only_ works for normalized E164 numbers.
Also, please don't open issues with examples that use completely fictional numbers.

Cheers
   Florian

**Comment by odedniv** [comment]
Hey @floere, this is not a fictional number, it's a valid local number in Israel (a little anonymized).

I allow my users to enter numbers in both local format and international format. When they provide a non-plausible number I just keep it as is, and when they provide a plausible number I allow myself to format it.

So I basically have something like this:

```ruby
def number=(number)
  super(Phony.plausible?(number) ? Phony.format(number) : number)
end
```

Which fails for the above number. How would you suggest implementing this?

Thanks

**Comment by floere** [comment]
Again,

> format only works for normalized E164 numbers.

So I suggest you normalize before formatting.
Note that Phony does not work for non-international numbers (i.e. local format).

Your basic way of doing this is ok, however I suggest you store a normalized E164 number in e.g. one DB field, and the user-provided number in another. When displaying the numbers, if you have a normalized number, render that one using Phony.format, otherwise just use the one as given.

Cheers & good luck! :rocket:

**Comment by odedniv** [comment]
How would I normalize the number? Shouldn't plausible tell me whether Phony can handle the string or not (international vs non-international)?

How can I know whether I will be able to use Phony.format or not?

**Comment by floere** [comment]
You can normalize an international number using `Phony.normalize`.

No, Phony can't discern a non-international and an international number, since in many cases, they do look the same.

You can use Phony.format if you have an E164 number.

**Comment by odedniv** [comment]
Well `Phony.normalize` doesn't really help me there...

```ruby
Phony.normalize("0508000000")
=> "508"
```

I guess I'll resort to checking if the number starts with `'0'` myself...

Thanks anyway

**Comment by floere** [comment]
Ok, you've piqued my interest. How non-fictional is that number? Would `0508000001` be an accepted number in Israel? My point is that if you use Phony with fantasy numbers (e.g. all zeroes), then it will of course not work.

**Comment by odedniv** [comment]
In Israel mobile numbers are 10 digits, in which the first 3/4 digits are the provider prefix.

The fact that it's all zeroes afterwards is irrelevant, the actual failing number didn't have zeroes but I didn't want to post it, but this is a completely valid number. Israeli numbers don't have a checksum or anything so the number after the provider code could be anything (one company even let new customers choose it when registering on their website).

The problem is actually with the fact that it's unfortunately starting with 8, which causes it to be plausible because it ignores the leading 0 thinking 508 is the country code, which is apparently valid. 0507000000 (which is also valid in Israel) make plausible return false (I guess 507 is not a valid country code? or wrong number of digits for that country?).
