### ISSUE TITLE
Argentina is not supported correctly.

### ISSUE THREAD

**Issue by alcuadrado** [floere/phony#310]
Argentina has two oddities on its phone number system, and they are not supported.

### After the `CC` (`54`) there's an optional `9`.

This `9` is not part of the `NDC` (it can't be used in local calls). 

And normally people use it only for phone numbers, but works for landlines too.

So these numbers are equivalent:

`549 (11) 66773399`
`54 (11) 66773399` 

### Mobile phone numbers have an optional `15` after the `NDC`.

So these numbers are equivalent:

`54 (11) 66773399` 
`54 (11) 1566773399` 

I don't have much experience with ruby, but I'm willing to add support for this if someone gives me a hint.

**Comment by floere** [comment]
@alcuadrado Hi Patricio – did you try adding it? If so, what were your questions? 😊

**Comment by alcuadrado** [comment]
Hi @floere, I'm afraid I haven't tried it. We are running on the JVM, so I used libphonenumber.

**Comment by floere** [comment]
@alcuadrado Ah, great you found something that works for you! Thanks for the feedback 😊
