### ISSUE TITLE
Normalize number based on Country's ISO Alpha 3 country code

### ISSUE THREAD

**Issue by brentdodell** [floere/phony#319]
Is there a way to pass the [ISO Alpha 3 country code](http://www.nationsonline.org/oneworld/country_code_list.htm) to `normalize` to get it to normalize the number as-is if possible, and if not, try prepending the telephone country code that matches the passed Alpha 3 code to the number and attempting to normalize that way?

Thanks

**Comment by floere** [comment]
@brentdodell Hi Brent! Is it known whether the passed number already includes the country code or not?

**Comment by brentdodell** [comment]
@floere some may, most probably don't. So no, it is not known.

**Comment by floere** [comment]
And any country or just e.g. US numbers?

On Sa., 09. Apr. 2016 at 15:06 Brent Odell

<
mailto:Brent Odell <notifications@github.com>
> wrote:

@floere some may, most probably don't. So no, it is not known.

**Comment by brentdodell** [comment]
Any country.

**Comment by floere** [comment]
Short answer: sadly no. You have to prepend it yourself before passing it to the `normalize` method.
