### ISSUE TITLE
Austrian number not recognized as plausible

### ISSUE THREAD

**Issue by fespinoza** [floere/phony#324]
What I did
----------

* `Phony.plausible? '+43 678 1220084'`

What happened
-------------

* this line returns `false`

What I expected to happen and why
---------------------------------

* that this phone number in particular return `true`, according to https://www.textmagic.com/free-tools/phone-validator this number should be correct. One of our austrian customers assures that this phone number is valid.

I am not aware of the full extent of the austrian phone rules, but an initial investigation shows that this number is indeed valid (tried with the twilio validator as well) and it seems an extra case `Phony` does not handle right now.

I'm happy to create a PR about it if we determine it's an actual issue.

**Comment by floere** [comment]
@fespinoza Thanks! 😊 This appears to be an actual issue as the NDC `678` is not existent in https://github.com/floere/phony/blob/master/lib/phony/countries/austria.rb#L48 and so it is handled using the fallback handler here https://github.com/floere/phony/blob/master/lib/phony/countries/austria.rb#L96.

I welcome your PR with tests – feel free to ask for help should you have trouble making it! 🚀

**Comment by fespinoza** [comment]
i will write a PR then :)
