### ISSUE TITLE
Add support for internal Russian phone style (8 926 ... instead of +7 926 ...) 

### ISSUE THREAD

**Issue by petRUShka** [floere/phony#329]
By some historical reasons the internal format for phone numbers is even more popular than the international format! And unfortunately it is completely unsupported by `phony` (and `phony_rails`) gem.

For example mobile number in international format '+7 926 1234567' a Russian citizen would likely write down as '8 926 1234567'.

The topic is discussed in Wikipedia article: https://en.wikipedia.org/wiki/Telephone_numbers_in_Russia

So instead of 

```
Phony.plausible?('89261234567')
=> false
Phony.normalize('89261234567')
=> "89261234567"
PhonyRails.normalize_number('8 926 1234567', country_code: 'RU')                                  
=> "+789261234567"
```

There should be something like this

```
Phony.plausible?('89261234567')
=> true
Phony.normalize('89261234567')
=> "79261234567"
PhonyRails.normalize_number('8 926 1234567', country_code: 'RU')                                  
=> "+79261234567"
```

As it have done with '+7'

```
Phony.normalize('+79261234567')
=> "79261234567"
Phony.plausible?('+79265550855')
=> true
PhonyRails.normalize_number('7 926 1234567', country_code: 'RU')                                  
=> "+79261234567"
```

Refer https://github.com/joost/phony_rails/issues/148

**Comment by floere** [comment]
Hi @petRUShka!

Thanks for your entry. As for your two Phony-related cases:

1. `Phony.plausible?('89261234567')` This case cannot be handled by Phony – it could not identify the number as from the Russian Federation. However, it may be worth a try to make the following possible: `rus = Phony["7"]; rus.plausible?("…")`
2. `Phony.normalize('89261234567')` Similarly to 1., we could try to make `rus = Phony["7"]; rus.normalize("…")` possible.

So, without providing Phony with a country code, it can't do much, but once provided, it could be possible – would that help?

**Comment by floere** [comment]
P.S: I can make the above work, but then 6 test cases added by earlier committers fail. Would you be happy to help with these?

**Comment by petRUShka** [comment]
Look, may be it is possible to understand that this is Russian phone number with 8.
1. It has 10 digits.
2. It has 8 at the beginning
3. It has allowed region code from list of Russian region codes. For example notation with 8 is mostly used together with mobile phones which is started from 9 and have limited number of options: e.g. 926, 903, 925...

**Comment by petRUShka** [comment]
For example it can be some option "try to recognize local Russian numbers". When it turned on the Phone can make a smart guess.

Yes, I can help. Which help do you have in mind?

**Comment by floere** [comment]
@petRUShka Thanks! I've changed the options in the commit https://github.com/floere/phony/commit/9fe7cbfb5e9b29e77b9aab853c4089a70a9d64e8 so that your examples would work. However, this results in spec failures. Would you mind checking them out (literally and figuratively), and reason with me whether the specs should be changed or not? (The specs have been added by other Russians)

If you fork and pull master, then run `rake`, `qed` and `rspec` are run, and 6 error cases should result.
