### ISSUE TITLE
Italian mobile phone

### ISSUE THREAD

**Issue by pascalineJulien** [floere/phony#330]
Hello, 

i wanted to know if it is possible to add zero=>false option on the match_split function.

Mobile phone does not have 0 when displaying in national format.

Phony.format('393885641630', :format => :national) => "0388 564 1630" but it think that it should display "388 564 1630"

Thank you

**Comment by floere** [comment]
Hi @pascalineJulien ! Sorry for the late answer 😓 Thanks for the issue – can you explain why it should be `388 564 1630`?

**Comment by pascalineJulien** [comment]
Hi Florian,

sorry too for late reply, it was one of my Italian customer who fire it out
to me.  He said that there is no more leading "0".

More over Wikidepia seems to say same thing

```
Mobile numbers prefix shortening[edit
<https://en.wikipedia.org/w/index.php?title=Telephone_numbers_in_Italy&action=edit&section=10>
]

Until 2001 a leading "0" was part of any mobile phone number, but it has
been removed.[5]
<https://en.wikipedia.org/wiki/Telephone_numbers_in_Italy#cite_note-5>

```


https://en.wikipedia.org/wiki/Telephone_numbers_in_Italy#Trunk_code_removal



2016-09-14 20:16 GMT+02:00 Florian R. Hanke <notifications@github.com>:

**Comment by floere** [comment]
@pascalineJulien What version are you using? Since `ruby -e 'require "phony"; p Phony.format("393885641630", :format => :national)'` results in `"388 564 1630"`. So, probably it has already been improved by a user 😊

**Comment by floere** [comment]
Ping @pascalineJulien ❓

**Comment by pascalineJulien** [comment]
Hi Flore

Of course i had an outdated version. My phony-rails is 0.9.1. But when i use to compare the lib files for italian country i have not seen any diff. I will try to update the gem and come to you again if the pbl still there. You can close the flow. 

Have a Nice day and thank you again

**Comment by floere** [comment]
@pascalineJulien Hi! It may be that the Phony core was changed, so that the Italian case may have been fixed (probably intentionally, since tests needed to be changed). Ok, thanks for your response, I'll close 😊 Have a nice day too! 🚀
