### ISSUE TITLE
Ecuador phone number format

### ISSUE THREAD

**Issue by baxter** [floere/phony#333]
Hi Floere, ordinarily I would create a PR but I've had a lot of trouble finding some clear rules for Ecuadorian numbers. I will document my findings below.

What I did
----------

* Tried to validate the number '+593 2 298 8300'

What happened
-------------

* The number did not pass validation

What I expected to happen and why
---------------------------------

* I expected this to pass (as did the customer who entered this number). I have tried to find evidence that this number is correct, but the documentation appears to me to say that this number is *not* correct. However, I have called this number and it worked. I also used Twilio's lookup service to validate the number, and it said that '+593 2 298 8300' was valid.
 * (Incidentally, the number '+593 68 467 4579', used in `plausibility_spec.rb` is not valid according to Twilio's lookup service)

I am happy to put together a PR if anyone knows where I can find some clear, up-to-date rules on Ecuadorian numbers! :smile:

**Comment by floere** [comment]
Excellent, thanks so much! 🙌
