### ISSUE TITLE
Some Finnish nationwide subscriber numbers not considered valid

### ISSUE THREAD

**Issue by tkalliom** [floere/phony#334]
The Regulation 32 of the Finnish Communications Regulatory Authority ([link](https://www.viestintavirasto.fi/attachments/maaraykset/Viestintavirasto32R2014M_EN.pdf)) states the maximum length of the significant part of nationwide subscriber numbers as ten digits. Among the codes which may begin a nationwide subscriber number are 029 and 07532[3-9].

What I did
----------
* `Phony::plausible?('+358295095050')`
* `Phony::plausible?('+358753252946')`

What happened
-------------
* `false`
* `false`

What I expected to happen and why
---------------------------------
* `true`, because the number is a real one
* `true`, because the number is a real one

**Comment by floere** [comment]
Hi @tkalliom ! Thanks for the nice issue entry – do you think you could provide a pull request improving the rules in https://github.com/floere/phony/blob/master/lib/phony/countries.rb#L633-L641 ? 😊
