### ISSUE TITLE
Return country code for a given number

### ISSUE THREAD

**Issue by ream88** [floere/phony#344]
Hey, how hard would it be to return the country for a given number? Something like https://github.com/alexrabarts/iso_country_codes I think it would be super easy to enhance your DSL to include country names as well.

**Comment by floere** [comment]
Hi @ream88 – it would be very easy. However, the stated goal is "to be able to normalize/format/split all phone numbers in the world.", and that is its focus and limit. Feel free to extend Phony with a gem of your own, if a country extension gem does not yet exist. The code would have to `split`, use the country code from the result, and use that to map it to a country (I assume you wanted a country ISO code).

Let me know please if you find/make a gem – I am happy to put it in the README as a gem using Phony. Cheers 🚀
