### ISSUE TITLE
Rule too restrictive for Austria

### ISSUE THREAD

**Issue by Olivier4murs** [floere/phony#358]
Important fact: *Phony only works with international phone numbers.* It needs the country code to be able to identify the number's country and rules.

What I did
----------

* Test : GRAND HOTEL EUROPA - Südtiroler Platz 2 A-6020 Innsbruck - Austria
+43 (0) 512 5931 

What happened
-------------

* Phony.plausible?('+43 512 5931') returns false

What I expected to happen and why
---------------------------------

* This phone number is ok, even if https://www.rtr.at/en/tk/E129/2312_Austrian_Numbering_Plan_2011-03-30.pdf say it's final number length should be 6..13

I tried to fix austria.rb :
- one_of(ndcs)             >> split(6..10)
+ one_of(ndcs)             >> split(3..10)

Thanks

**Comment by floere** [comment]
Hi @Olivier4murs! What happened when you changed it to `one_of(ndcs) >> split(3..10)`?
