### ISSUE TITLE
+61 phone number formatting broken (regression)

### ISSUE THREAD

**Issue by jashank** [floere/phony#361]
Dropping the trunk digit for 13/1800 numbers per #339 has, it seems, broken _every other_ phone number.

    > ph = "61255501053";
    > Phony.format ph
    => "+61 2 5550 1053"
    > Phony.format ph, format: :national, country: "AU"
    => "2 5550 1053"

I'll hack up some tests and a PR shortly.

**Comment by jashank** [comment]
I've had several attempts at getting this to work, and I can't come up with an elegant solution that covers the (effectively) three cases.  I have a hunch that I've missed something very obvious, but the only thing that currently makes sense is some sort of gross hack to push the trunk code into the NDC...

**Comment by floere** [comment]
@jashank Jeremy, thanks for your efforts so far – can you formulate this as a PR on this repo so I can have a look as well (and have your work be acknowledged properly)? Thanks 😊

**Comment by floere** [comment]
@jashank P.S: Sorry for the late response, btw. I do check the PRs more regularly than the issues. I've asked the issue opener on #339 to provide some info on why the change was needed, so that we can move forward with a solution based on all the info we can get.
