### ISSUE TITLE
Normalization is dropping third 0 digit

### ISSUE THREAD

**Issue by dbeqiraj** [floere/phony#373]
Important fact: *Phony only works with international phone numbers.* It needs the country code to be able to identify the number's country and rules.

#  What I did
`Phony.normalize('(330) 458-1111')`
`Phony.normalize('(700) 458-1111')`

# **What happened**
`=> '334581111'`
`=> '7004581111'`

#  What I expected to happen and why
`=> '3304581111'`
`=> '7004581111'`

**Comment by floere** [comment]
Did you see the important fact?

**Comment by dbeqiraj** [comment]
No :P 
So... nothing to do, right?

**Comment by floere** [comment]
Probably not 😊 Unless there's something else?
