### ISSUE TITLE
Does not handle Indonesian number with 13 digits

### ISSUE THREAD

**Issue by yusufsyaifudin** [floere/phony#374]
In Indonesia, there is some mobile operator which issued phone number with 13 lengths and it is should be valid. 

But, this fails even though it is a valid number `Phony.plausible?("+61895378490136")`.

Perhaps I can change code in https://github.com/floere/phony/blob/master/lib/phony/countries/indonesia.rb#L36 to `/\A\d{7}\z/ => [3,4..5],` and make a pull request, but I'm not sure it supposed to be there, even it looks like solved issue #182.

**Comment by floere** [comment]
@yusufsyaifudin Please make the PR, thanks :)
