### ISSUE TITLE
Cayman Islands Support

### ISSUE THREAD

**Issue by duane** [floere/phony#377]
To my understanding, the Cayman Islands have a "country code" of 1-345—but this is virtually indistinguishable from the US area code 1 (345) XXX-XXXX. This interferes with e.g. formatting the "national" number, which (to my understanding) would be something like `["1345", false, "XXX", "XXXX"]`.

How would I go about adding support for ky to phony? At first blush it appears to split them as american numbers with a cc of `+1`.

**Comment by floere** [comment]
Hi @duane! Thanks for your issue. Under the NANP (https://en.wikipedia.org/wiki/North_American_Numbering_Plan), the CC is not really a country code, but just the code for North America, including the Caribbean. Therefore, the countries are represented as areas. Most "island countries" have just one area code, as do the Cayman Islands.

So this is fine:

```
ruby -e 'require "phony"; p Phony.split("13451231234")'
["1", "345", "123", "1234"]
```

Cheers!

**Comment by duane** [comment]
This was quite helpful back in june. Thanks @floere!

**Comment by floere** [comment]
@duane My pleasure, Duane! 😃
