### ISSUE TITLE
Croatia too restrictive

### ISSUE THREAD

**Issue by pzupan** [floere/phony#379]
I have a user trying to enter his croation telephone number +385 98 352 085 and it is being rejected.

**Comment by floere** [comment]
Which version is this about?

**Comment by pzupan** [comment]
Sorry.   2.15.43

**Comment by floere** [comment]
Could you try 2.15.45 and report back, please?

**Comment by pzupan** [comment]
Still getting the error with 2.15.45.  
{:phone=>[{:error=>:improbable_phone}]}

**Comment by floere** [comment]
@saner @ronin Can you help with this issue? :) (Croatia just got an update via https://github.com/floere/phony/pull/375, however this issue existed pre-update as well)

**Comment by pzupan** [comment]
Hold on.  I'm doing some further testing.  This could be an issue with phony_rails...

**Comment by ronin** [comment]
@pzupan @floere @saner I've checked this number on version 2.15.45 (sha fd09a14ced90dde1316b988b5001a78665632559) and it is accepted.

```
main:0> Phony.normalize "+385 98 352 085"
=> "38598352085"
main:0> Phony.plausible? "+385 98 352 085"
=> true
```

**Comment by pzupan** [comment]
Phony.plausible? "+385 98 352 085" is failing in phony_rails as the local splitter is looking for a length of 7 and the remainder after the national splitter is 6.  

```
# lib/phony/local_splitters/fixed.rb 50
def plausible? rest, hints = {}
     @length === rest.inject(0) { |total, part| total + part.size }
end
```
I haven't tracked down how the splitter is working yet, but I think the template in croatia.rb is:
`match(/^(9\d)/)     >> split(3, 3..4)    | # Mobile`
Should this result in a @length of 6?
