### ISSUE TITLE
NoMethodError: undefined method `split' for 1:Integer

### ISSUE THREAD

**Issue by Dorian** [floere/phony#385]
What I did
----------

* `Phony.split('0123456789')`

What happened
-------------

> NoMethodError: undefined method `split' for 1:Integer

What I expected to happen and why
---------------------------------

* Some `ArgumentError` because it's not a plausible number
* or trim zeros and split that
* or ??? (I don't know :D)

**Comment by erikdstock** [comment]
Same.

**Comment by floere** [comment]
I'm fascinated by the number of people entering a number that is clearly not supported, but I can see the case for an `ArgumentError`, if that truly would improve your life 😊

**Comment by erikdstock** [comment]
Sorry, to give more context- I was looking for a gem that would be able to validate/format an arbitrary phone number that a user entered on signup, failing or returning `nil` if the number was not plausible. Maybe I'm misunderstanding the purpose of this library, though.

**Comment by Dorian** [comment]
@floere Bettter catch an `ArgumentError` than catch for any type of error IMHO

**Comment by floere** [comment]
@Dorian @erikdstock Thanks for your input! 😊 I've implemented `ArgumentError` variants `NormalizationError`, `SplittingError`, `FormattingError`. Released in 2.16.0 🚀

**Comment by Dorian** [comment]
@floere Nice! Thanks a lot!
