### ISSUE TITLE
Silence warnings

### ISSUE THREAD

**Issue by lloeki** [floere/phony#387]
What I did
----------

Run tests of a project depending on phony. 

What happened
-------------

There were warnings from the phony dependency in the output:

```
/Users/lloeki/.gem/ruby/2.3.4/gems/phony-2.15.47/lib/phony/country_codes.rb:80: warning: assigned but unused variable - trunk
```

What I expected to happen and why
---------------------------------

No warnings

Suggested cause and approach
--------------------------------

This is because with a recent rake (>=11.0), ruby warnings are now on by default.

What do you think about fixing those warnings as well as running the test suite with `ruby -w` / `$VERBOSE = true` / `t.warning = true` ?

**Comment by floere** [comment]
Hi @lloeki – sorry for the late response! When using rake, the test suite already runs with warnings on. As there are numerous warnings from used libraries, I must have missed the one from Phony. Thanks for the pointer! Not showing up anymore in the latest version. Also, thanks for the nice writeup 😊
