### ISSUE TITLE
Costa Rica incorrect format

### ISSUE THREAD

**Issue by ghost** [floere/phony#392]
Important fact: *Phony only works with international phone numbers.* It needs the country code to be able to identify the number's country and rules.

What I did
----------

* Added my Costa Rica number (+506 XXXX-XXXX) 

What happened
-------------

* The number was formatted as +506-X-XXX-XXXX

What I expected to happen and why
---------------------------------

* The correct formatting for 8 digit numbers in Costa Rica is +506 XXXX-XXXX, which is what I would expect to see.

**Comment by floere** [comment]
@bububullon Thanks for the clean Issue entry. Would you care to do something about it? https://github.com/floere/phony/blob/master/CONTRIBUTING.md 😊
