### ISSUE TITLE
Invalid evaluation of phone numbers in Macau

### ISSUE THREAD

**Issue by willzoltan** [floere/phony#395]
What I did
----------

Tried to validate a customer's phone number in Macau:

Phony.plausible?('+8536203XXXX', cc: 'MO')

What happened
-------------

This returns false.

What I expected to happen and why
---------------------------------
I expected this to return true. The customer assures us that this is their correct phone number and that this is valid. I checked Wikipedia and found that this is indeed a valid number in Macau: https://en.wikipedia.org/wiki/Telephone_numbers_in_Macau

Thanks in advance for your help!

**Comment by floere** [comment]
Hi Will, the cc option requires a country code, e.g. 41 for Switzerland.
Cheers! 😊

**Comment by willzoltan** [comment]
Hi floere, 853 is the country code for Macau
Cheers :)

**Comment by floere** [comment]
Thanks! Does it then work? (If you pass it cc: 853)

**Comment by willzoltan** [comment]
Indeed so! Apologies, I'm really sorry for wasting your time. Thanks for your help!

**Comment by floere** [comment]
@willzoltan Not a problem at all, have a great day! 😊
