### ISSUE TITLE
Sat phone support / failing test cases

### ISSUE THREAD

**Issue by scottfromsf** [floere/phony#404]
Important fact: *Phony only works with international phone numbers.* It needs the country code to be able to identify the number's country and rules.

What I did
----------
I have an application that needs to support satellite phones (e.g. Iridium) and well-formed numbers don't validate with this library. For example, ‭+881632647870‬.

On my fork I've added what I think is the right code to properly support sat phones based on the numbering plan described here: https://www.numberingplans.com/?page=plans&sub=phonenr&alpha_2_input=QM. Unfortunately the QED tests use the 881 CC as test input for "Unsupported Countries" in `qed/format.md` so the tests are now failing given that I've added support.

What I expected to happen and why
---------------------------------
I expected to add my own tests to verify mainline and edge cases for sat phones (e.g. Iridium vs. Ellipso use different formats), but the existing tests assume +881 is always a 10-digit NDC+SN and are failing. Specifically, the test case for the number "+881 32155605 220" isn't valid since the number isn't the correct length (see numberplans.com link above).

My question here is what is trying to be achieved by the "Unsupported Countries" tests in `qed/format.md` and how should still address those aims while properly supporting +881?

**Comment by scottfromsf** [comment]
BTW, here's the commit that breaks the tests: https://github.com/scottfromsf/phony/commit/8423f6b5fea3cb3d5c92082839720f5caa1fe561

Again, all I'm asking is how to I change the existing tests while preserving what they're trying to achieve. Maybe as simple as using a different CC and text numbers?

**Comment by scottfromsf** [comment]
I went ahead and changed the 'unsupported countries' tests to use the 882 CC and have submitted PR #405

**Comment by floere** [comment]
What you did is perfectly right – what was once unsupported is now sat phones. Thanks again 😊
