### ISSUE TITLE
Recognize Sofia, Bulgaria numbers

### ISSUE THREAD

**Issue by davidkovsky** [floere/phony#408]
Important fact: *Phony only works with international phone numbers.* It needs the country code to be able to identify the number's country and rules.

What I did
----------

* Tried to validate that a valid number for Sofia is plausible (+359 2 928 4500).

What happened
-------------

* Phony.plausible? was not recognizing Sofia numbers (example: +359 2 928 4500). After digging deeper, I found that Phony was formatting Bulgarian numbers incorrectly according to http://www.wtng.info/wtng-359-bg.html. 

What I expected to happen and why
---------------------------------

* 2.3.5 :007 > n1
 => "+359 87 8357500"
2.3.5 :008 > Phony.plausible?(n1)
 => true
2.3.5 :009 > Phony.normalize(n1)
 => "359878357500"
2.3.5 :010 > Phony.format(Phony.normalize(n1))
 => "+359 87 8357500"
2.3.5 :011 > n2
 => "+359 2 9284500"
2.3.5 :012 > Phony.plausible?(n2)
 => true
2.3.5 :013 > Phony.format(Phony.normalize(n2))
 => "+359 2 9284500"

I'll submit a PR for this soon.

**Comment by davidkovsky** [comment]
I forgot to close the loop. Here's the PR: https://github.com/floere/phony/pull/409

**Comment by floere** [comment]
@davidkovsky Thanks for the nice issue entry I responded on the PR 😊

**Comment by davidkovsky** [comment]
I closed PR 409 and opened https://github.com/floere/phony/pull/412 to keep the history clean.

**Comment by floere** [comment]
Thanks! 😊
