### ISSUE TITLE
Version Tags Missing (v2.16.6...)

### ISSUE THREAD

**Issue by widescape** [floere/phony#426]
I wanted to see what the newest version v2.16.10 does differently than v2.16.9 in order to decide if I should upgrade the gem version in my project now or later.

RubyGems lists versions **v2.16.6 upwards**: https://rubygems.org/gems/phony/versions

GitHub lists release versions **only up to v2.16.5**: https://github.com/floere/phony/releases

This does not allow a comparison like https://github.com/floere/phony/compare/v2.16.9...v2.16.10

Could you please tag the released gem versions? Thank you.

**Comment by floere** [comment]
Hi @widescape – thanks for the issue 👍 I did not push the tags – they were only locally available. Now you should be able to see them. Thanks again! 🎉

**Comment by widescape** [comment]
Perfect! Thank you. 🙏
