### ISSUE TITLE
Phony.plausible? crash for Italian numbers

### ISSUE THREAD

**Issue by zedalaye** [floere/phony#428]
Using latest Phony 2.16.11

What I did
----------

 ````ruby
Phony['39'].plausible?('12345')
````

What happened
-------------

````
NoMethodError (undefined method `plausible?' for nil:NilClass)
````

What I expected to happen and why
---------------------------------

Returns true or false because it works with French phony even with invalid numbers :

````ruby
irb(main):025:0> Phony['33'].plausible?('12345')
=> false
````

**Comment by floere** [comment]
@zedalaye Thanks for reporting, Pierre! 👍 Fixed and released in 2.17.0 🚀
