### ISSUE TITLE
Some German numbers converted from the GDR network not recognized

### ISSUE THREAD

**Issue by sroller** [floere/phony#429]
Important fact: *Phony only works with international phone numbers.* It needs the country code to be able to identify the number's country and rules.

What I did
----------
Phony.split('+493995620412')

What happened
-------------
Phony could not split the given number. Is "+493995620412" a phone number?

What I expected to happen and why
---------------------------------
the number should be split in 
country=49
area code/ndc=39956
subscriber=20412

there are several areas in the Eastern part of Mecklenburg-Vorpommern which have 5-digit area codes.

**Comment by floere** [comment]
Hi @sroller, I initially misunderstood – in this case, simply lose the `+`.
