### ISSUE TITLE
Possible to detect presence of phone number in a longer string?

### ISSUE THREAD

**Issue by adambedford** [floere/phony#430]
Is it possible to detect (and ultimately strip out) a phone number from a longer string? I'm basically trying to redact phone numbers from messages exchanged on a platform. Wondering if all the awesome logic in this app could be leveraged for this.

Thanks in advance for any guidance.

**Comment by floere** [comment]
Hi @adambedford! This is a very interesting problem – Phony does not have anything for searching phone numbers. However, for deciding whether something is a phone number, it does. So I'd suggest to use a regexp based `String#scan` to detect possible phone numbers (for the structure, see https://github.com/floere/phony#description), then iterating through them using Phony to check if they are indeed phone numbers.
