### ISSUE TITLE
Phony.plausible? not recognizing Israeli numbers

### ISSUE THREAD

**Issue by sergeydgr8** [floere/phony#435]
It seems like `Phony.plausible?` returns false for Israeli phone numbers. I've tried using "9710xxxxxxxxx" (10 digit) and "971xxxxxxxxx" (9 digit) format, both of which Phony does parse out and normalize correctly, however `.plausible?` will always return false. This seems to have been messing with our validations.

Funny enough, running `Phony.plausible?(Phony.normalize('9720511234567'))` also returns false.

**Comment by floere** [comment]
Hi @sergeydgr8 – 971 is the CC for the UAE. I assume you mean 972? If so, what do you mean by `always`?

The last example is not defined in Phony:

```ruby
  country '972',
    trunk('0') |
    one_of('1')                            >> split(3,3,3) | # special numbers
    one_of('2', '3', '4', '8', '9')        >> split(3,4)   | # 1 digit ndc
    match(/^(5[023456789]|7[23467])\d+$/)  >> split(3,4)     # 2 digit ndc
```

`51` as an NDC is not matched by the last rule and the rules do not define a fallback. Does Phony need a rules update for Israel?

**Comment by sergeydgr8** [comment]
Ah yes, I definitely meant 972!

And yes to the latter. Phony would need an update to handle `051` codes.

**Comment by sergeydgr8** [comment]
As described in this table: https://en.wikipedia.org/wiki/Telephone_numbers_in_Israel#Cellular_and_mobile_devices_area_code_05

**Comment by floere** [comment]
Thanks! 😊 If you'd like to belong to the contributors, I really welcome PRs, even small ones (like this one) – would you be up for it?

**Comment by sergeydgr8** [comment]
Sure thing :)

**Comment by floere** [comment]
👍
