### ISSUE TITLE
Numbers from Argentina: Validation faulty

### ISSUE THREAD

**Issue by sbiastoch** [floere/phony#439]
What I did
----------
`Phony.plausible?('+54-3546 12345678')`

What happened
-------------
`False`

What I expected to happen and why
---------------------------------
`True`. According to http://www.wtng.info/wtng-54-ar.html the number is valid since the number has a valid area code 3546 (see http://www.wtng.info/ccod-53.html#CC54) and an 8 digit subscriber code.

Are my information outdated or is it a bug? Thanks for your help and this awesome gem!

**Comment by floere** [comment]
@sbiastoch Thanks Stephen! 😊 It's well possible that Phony is not quite up to date. Would you mind updating Phony and submitting a PR? (The definition for Argentina is in `countries.rb`)
