### ISSUE TITLE
plausible? returns true for invalid USA numbers

### ISSUE THREAD

**Issue by fluffyx** [floere/phony#445]
plausible? returns true for these, but they are invalid:

+1 (?11) ???-????
+1 (???) ?11-????
+1 (???) 1??-????
+1 (???) 0??-????

Same for this set of 555 numbers. Every one of these is reserved for "example" phone numbers, to be used in movies, for instance. They will never be a working number.

+1 (???) 555-01??
+1 (800) 555-????
+1 (822) 555-????
+1 (833) 555-????
+1 (844) 555-????
+1 (855) 555-????
+1 (866) 555-????
+1 (877) 555-????
+1 (888) 555-????
+1 (555) ???-????

Numbers matching the following pattern are usually fake because movies tend to stray outside of the officially reserved +1 (???) 555-01?? zone, but I read that some areas which have run out of other numbers have begun to use them. I've never seen it in real life.

+1 (???) 555-????

The following number is for directory assistance. It will never be a real user's phone number.

+1 (???) 555-1212

You may find that the last two examples are outside of the scope of phony and should be handled by the application. But all other examples should return false when calling plausible?.

Thank you for your consideration!

**Comment by floere** [comment]
Hi @fluffyx – apologies for the late answer and thanks for the issue.

Phony is more about whether a number is valid under the various numbering plans (NANP in this case), and not whether it is a working number. A small note regarding `555`, "the only […] numbers now specifically reserved for fictional use are 555-0100 through 555-0199" (https://en.wikipedia.org/wiki/North_American_Numbering_Plan#Special_numbers_and_codes)

Is the issue people leaving fictional numbers in e.g. your app?
