### ISSUE TITLE
Phony.plausible returns false for valid german phone number

### ISSUE THREAD

**Issue by fschwahn** [floere/phony#447]
What I did
----------

* `Phony.plausible?("+49691551")`

What happened
-------------

* Returns false

What I expected to happen and why
---------------------------------

* I expect it to return true. This is the official number of Hessischer Rundfunk, which is the public broadcasting corporation of the German federal state of Hessen (see https://www.hr.de/impressum/index.html)

**Comment by floere** [comment]
@fschwahn Hi! Apologies for the late answer (summer break) – and thanks – this must be the shortest German number I've ever seen 😄 Fix released in 2.18.7 🚀

**Comment by fschwahn** [comment]
Yes, me too 😄 Unfortunately it was entered in our app 🙄😄 Thanks for the fix!

**Comment by floere** [comment]
My pleasure! 😊
