### ISSUE TITLE
Leading 0 incorrectly suppressed from Sammarinese numbers

### ISSUE THREAD

**Issue by skateinmars** [floere/phony#449]
What I did
----------

`Phony.normalize '+3780549903549'`

What happened
-------------

`378549903549`

What I expected to happen and why
---------------------------------

`3780549903549`

The 0 was stripped but should have stayed included since it is part of the area code. See https://en.wikipedia.org/wiki/Telephone_numbers_in_Italy#San_Marino

I tested Twilio and the google libphonenumber lib and they both respect this.
As a bonus, they also both add the area code when not provided, so `+378903549` get turned into `+3780549903549` automatically.

**Comment by floere** [comment]
Thanks @skateinmars! 😊 Released in 2.18.9 🚀

**Comment by skateinmars** [comment]
Thanks a lot for the reactivity! :racing_car:
