### ISSUE TITLE
Incomplete detection of Nigerian phone numbers

### ISSUE THREAD

**Issue by skateinmars** [floere/phony#450]
What I did
----------

`Phony.plausible? '+23464830000'`

What happened
-------------

`false`

What I expected to happen and why
---------------------------------

`true`

https://www.ncc.gov.ng/technical-regulation/standards/numbering (& Wikipedia) mention area codes ranging from 30 to 89, but Phony seems to only recognize 1, 2 and 9 (+ mobile phones).

This one may be more of a question than an actual bug report :sweat_smile: it was found by one of our QA engineers during testing, but after some quick browsing on Google Maps I could not find any actual number using one of those area codes.

Twilio lookup does recognize the number tested in the example and correctly detects the carrier name.

**Comment by floere** [comment]
Hi @skateinmars!

Thanks for the issue 😊
Would you mind taking a shot at improving the rules in `countries.rb` yourself and opening a PR?

Here are the current rules:

```
  # Nigeria
  # Wikipedia says 3 4 split, many local number with no splitting
  #
  # mobile telephony number allocation taken from: http://www.ncc.gov.ng/index.php?option=com_content&view=article&id=113&Itemid=102
  country '234',
    match(/^([7-9]0\d)\d+$/) >> split(3,4) | # Mobile
    match(/^(81\d)\d+$/)     >> split(3,4) | # Mobile
    one_of('1', '2', '9')    >> split(3,4) | # Lagos, Ibadan and Abuja
    fixed(2)                 >> split(3,4)   # 2-digit NDC
```

Cheers! 😊
