### ISSUE TITLE
Phony.plausible? returns false for a valid Gabon number

### ISSUE THREAD

**Issue by Startouf** [floere/phony#461]
_Important fact: *Phony only works with international phone numbers.* It needs the country code to be able to identify the number's country and rules._

What I did
----------

* Attempt to save a valid Gabon phone number +241 74 xx xx xx ( so 24174xxxxxx after normalize)

What happened
-------------

* Does not work (Phony.plausible? return false even after bumbing gem to latest version)

What I expected to happen and why
---------------------------------
It should consider the phone number valid 

Related info
* https://www.panapress.com/Gabon-changes-number-of-digits-o-a_630616143-lang2.html
* https://en.wikipedia.org/wiki/Telephone_numbers_in_Gabon

**Comment by floere** [comment]
Hi @Startouf! Would you mind contributing via a PR? 😊
