### ISSUE TITLE
Phony.plausible? returns false for a valid Belgian mobile phone number

### ISSUE THREAD

**Issue by charlottepages** [floere/phony#466]
Important fact: *Phony only works with international phone numbers.* It needs the country code to be able to identify the number's country and rules.

What I did
----------

- Attempted to save a valid begian mobile phone number
- Checked I was on the gem's latest version

What happened
-------------

Failed to validate & save the number because `Phony.plausible?` returned `false`
``` 
Phony.plausible?('0411 22 33 44', country_code: 'BE')
Phony.plausible?('0411223344', country_code: 'BE')
Phony.plausible?('+32411223344', country_code: 'BE')
Phony.plausible?('0032411223344', country_code: 'BE')
=> false
```

What I expected to happen and why
---------------------------------

Expected `Phony.plausible?` to return `true` since '0411 22 33 44' is a valid Belgian phone number format
https://en.wikipedia.org/wiki/Telephone_numbers_in_Belgium
> 04xx xx xx xx - dialing a mobile number from a land line or another mobile phone.

**Comment by floere** [comment]
Hi @charlottepages! Thanks very much for the issue 😊 It appears a service is missing in `countries.rb` for Belgium. Would you be up for fixing this and making a PR?

The relevant part in `countries.rb`:

```ruby
  country '32', trunk('0') |
                match(/^(7[08])\d+$/)       >> split(3,3)   | # Premium and national rate Services
                match(/^(800|90\d)\d+$/)    >> split(2,3)   | # Toll free service and premium numbers
                match(/^(46[05678])\d{6}$/) >> split(2,2,2) | # Mobile (Lycamobile, Telenet, Join Experience, Proximus 0460)
                match(/^(4[789]\d)\d{6}$/)  >> split(2,2,2) | # Mobile
                match(/^(45[56])\d{6}$/)    >> split(2,2,2) | # Mobile Vikings and Voo
                one_of('2','3','4','9')     >> split(3,2,2) | # Short NDCs
                fixed(2)                    >> split(2,2,2)   # 2-digit NDCs
```

**Comment by charlottepages** [comment]
Hi @floere will do, thx !

**Comment by charlottepages** [comment]
https://github.com/floere/phony/pull/468

Linked issue: https://github.com/floere/phony/issues/466

Looking into Belgian carriers attributed GSM range (https://en.wikipedia.org/wiki/Telephone_numbers_in_Belgium#Mobile_numbers),
it turns out '0411 22 33 44' is **_not_** be a plausible number
for only the following range have been attributed as of today:
```
0455: GSM. Range is owned by VOO; however subscriber may have been ported to another network
0456: GSM. Range is owned by MobileViking; however subscriber may have been ported to another network
0460: GSM. Range is owned by Proximus; however subscriber may have been ported to another network
0465: GSM. Range is owned by Lycamobile; however subscriber may have been ported to another network
0466: GSM. Range is owned by Vectone; however subscriber may have been ported to another network
0467: GSM. Range is owned by Telenet; however subscriber may have been ported to another network
0468: GSM. Range is owned by Telenet; however subscriber may have been ported to another network
047-: GSM. Range is owned by Proximus; however subscriber may have been ported to another network
048-: GSM Range is owned by Telenet (Base); however subscriber may have been ported to another network
049-: GSM Range is owned by Orange; however subscriber may have been ported to another network
```

👉 added a few specs & qed to complete the doc.
Fill free to close without merge if you wish ;)

**Comment by floere** [comment]
Thanks again – PR is merged, closing 😊
