### ISSUE TITLE
warning: Capturing the given block using Proc.new is deprecated; use `&block` instead

### ISSUE THREAD

**Issue by MohammedAbuissa** [floere/phony#467]
What I did
----------
Upgraded ruby to 2.7.0 

What happened
-------------
I got a lot of warnings saying 

> gems/phony-2.12.14/lib/phony/dsl.rb:17: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead

When I start the server.

What I expected to happen and why
---------------------------------
Warnings shouldn't appear as they affect performance and flood the log files.

**Comment by floere** [comment]
@MohammedAbuissa Thanks for the issue! I notice you're using a version of the gem that is from May 09, 2015. Is it possible for you to upgrade to a later version? Cheers! 😊

**Comment by MohammedAbuissa** [comment]
@floere works like charm, thanks!
