### ISSUE TITLE
Phony.plausible? returns false for a valid Belgian phone number

### ISSUE THREAD

**Issue by AnnaKai** [floere/phony#476]
What I did
----------

Attempted to save a valid phone number
Checked I was on the gem's latest version
Read [this similar issue](https://github.com/floere/phony/issues/466).

What happened
-------------

Failed to save a Belgian phone number with area code `63` / `063`
```
Phony.plausible?('+32 63 949 08 17', country_code: 'BE')
Phony.plausible?('+32 063 949 08 17', country_code: 'BE')
Phony.plausible?('63 949 08 17', country_code: 'BE')
Phony.plausible?('639490817', country_code: 'BE')
Phony.plausible?('+32639490817', country_code: 'BE')
Phony.plausible?('32639490817', country_code: 'BE') 
=> false
```
What I expected to happen and why
---------------------------------

According to wiki, 63 is a valid area code in Belgium and according to http://www.wtng.info/wtng-32-be.html subscriber number can be 7 digits. So, I expected `Phony.plausible?` to return `true`

**Comment by AnnaKai** [comment]
Sorry, it was client's mistake

**Comment by floere** [comment]
@AnnaKai No problem! 😊
