### ISSUE TITLE
Numbering plan of Cote d'Ivoire/Ivory Coast has changed

### ISSUE THREAD

**Issue by wthys** [floere/phony#477]
Important fact: *Phony only works with international phone numbers.* It needs the country code to be able to identify the number's country and rules.

What I did
----------

* Use Phony on Ivory Coast numbers after the numbering plan change of Jan 31, 2021 (8 digits became 10 digits)

What happened
-------------

* new correct numbers are plausible.

What I expected to happen and why
---------------------------------

* new correct numbers are plausible

**Comment by floere** [comment]
Handled in #478 by @wthys
