### ISSUE TITLE
Phony plausible? returns false for 3 digit locals with 3 digit NDC (German Numbers)

### ISSUE THREAD

**Issue by Fleick** [floere/phony#484]
What I did
----------

* I tried to plaubsible the numbers of Bayer (big german chemical group) 49 214 301 (https://www.bayer.com/de/impressum) and the University of Münster 49 251 830 (https://www.uni-muenster.de/de/)

What happened
-------------

* Phony.plausible?("49214301") resp. Phony.plausible?("49251830") returns false.

What I expected to happen and why
---------------------------------

* It should be returned true as they are valid numbers in use - see sources above.  
I think it comes from the fact that the [wiki entry in the countries file](https://en.wikipedia.org/wiki/Telephone_numbers_in_Germany) says: "Grandfathered numbers may be as short as four digits (seven total).". This is not complete, there are also older numbers with only 3 local digits.

**Comment by floere** [comment]
@Fleick Danke, Florian. D.h. es existieren noch Nummern der Länge 8 und grösser. Hast du Zeit/Lust, einen PR für die Deutschen Nummern zu machen?

**Comment by floere** [comment]
Note to self: This may be a good case for a non-E164-standard mode.

Something like either of:

```
Phony.switch_to_non_standard_mode!
Phony.switch_to_non_e164_mode!
```

Unsure how to do the API for this though, as it could mean lots of extra definitions that need to be maintained.

**Comment by floere** [comment]
> Würde mich aber freuen wenn es hier eine Lösung geben würde, wobei sich ein non-E164 mode leider tatsächlich nach einiger Arbeit anhört :/

Danke für die Infos, ich hoffe, es läuft bei Dir bald stressfreier 😊

Würde es Dir helfen, wenn `plausible?` zB eine Option wie `Phony.plausible?("49214301", check_length: false)` anbietet?
Ich denke daran herum, dass man so wenigstens in spezifischen begründeten Fällen diese Prüfung aushebeln könnte. Bin noch nicht ganz sicher, obs tatsächlich geht, aber es sollte.

**Comment by floere** [comment]
As a test, I've added an option: https://github.com/floere/phony/blob/master/qed/plausibility.md?plain=1#L516-L520 (not yet sure if it's the way to go) If you have feedback, please let me know.
