### ISSUE TITLE
Samoa valid number that starts with "71" was not validated

### ISSUE THREAD

**Issue by betogrun** [floere/phony#496]
What I did
----------

* I tried to validate a valid phone number from Samoa that starts with "71".

What happened
-------------

* The validation returned false.

What I expected to happen and why
---------------------------------

* The validation should have returned true because this is a valid number.

**Comment by floere** [comment]
@betogrun What was the number? Feel free to anonymize the last 4 digits (xxxx).

**Comment by betogrun** [comment]
@floere the number is "718xxxx". I have other examples like "716xxxx" and "713xxxx" that also return false.
