### ISSUE TITLE
Phony.plausible? returns false for valid Columbian numbers

### ISSUE THREAD

**Issue by ewamarciniak** [floere/phony#500]
What I did
----------
Attempted to save a valid phone number
Checked I was on the gem's latest version

What happened
-------------

* Failed to save a Columbian phone number with area code 601
Phony.plausible?('+57 601 411 1899', country_code: 'CO')
Phony.plausible?('+576014111899', country_code: 'CO')
Phony.plausible?('576014111899', country_code: 'CO')

=> false

What I expected to happen and why
---------------------------------

* According to wiki, 601 is a valid area code in Columbia and also [this source](https://support.freshcaller.com/en/support/solutions/articles/50000003692-columbian-phone-numbers-update) states that numbers in Columbia recently migrated from 8 digits to 10 digits. So I expected Phony.plausible? to return true.

**Comment by floere** [comment]
Hi @ewamarciniak! Thanks for the issue 😊

Do you feel up to the task of providing an improvement via pull request? The relevant code is here: https://github.com/floere/phony/blob/master/lib/phony/countries.rb#L231-L235

Also, note that `Phony.plausible?('+57 601 411 1899')` takes `cc` or `ndc` options as telephone country codes ('1' = North America and so on). See https://github.com/floere/phony/blob/master/qed/plausibility.md#options for details. In your case, a `cc` may not be needed (it depends if you'd like to make sure it's a colombian number).

Thanks again!

**Comment by davemcginnzendesk** [comment]
Hi @floere , I work with @ewamarciniak and I created a merge request addressing this issue. Please take a look when you get a chance. Many thanks

https://github.com/floere/phony/pull/501
