### ISSUE TITLE
Proposal for "no RAM" mode

### ISSUE THREAD

**Issue by maxim** [floere/phony#504]
In a project where you don't check phones often, but you want to include all countries, you'd probably prefer to save RAM, and make look ups directly from disk.

I made a low-level gem that performs efficient disk lookups using binary search, without using any RAM ([wordmap](https://github.com/scottscheapflights/wordmap)). It is used in production (last I know of) to make lookups of multi-megabyte datasets.

The config data of phony seems to be a great fit for wordmap format. We could make a rake task to dump wordmaps from existing configs, and ship them with the gem. Then we'd introduce an out-of-the-box "no-RAM" option for those who perform infrequent lookups of all numbers. Would you want this in the gem?

Alternatively, I could make a separate gem that changes how Phony does lookups. If you prefer this approach, do you have any advice on where in the code would be a good integration point for altering config lookups?

**Comment by floere** [comment]
Hi @maxim!

Thank you for your proposal! Even though phony only uses roughly 1 MB, I can see your use case.

I don't think this is a great fit for the gem itself (it's not core to the goal of the gem), but a separate gem would be excellent.

Would it be possible to do something like:

```
require 'wordmap'

Wordmap.with_replaced_hashes('path/to/dir') do
  require 'phony'
end
```

And it would hook into Hash creation for the context of the `with_replaced_hashes` block and use random (?) file names whenever any code inside creates a Hash, it will instead create a wordmap. Just as an idea – too extreme?

**Comment by floere** [comment]
@maxim I hope you're not discouraged to do it – if you put something out there, I will definitely link to it in the README for others with your use case to use! 😊

**Comment by maxim** [comment]
Not at all, I'm also kind of on the fence purely from the engineering perspective. Want to think it through a bit more.
