### ISSUE TITLE
Dial code not added when the phone number has just the leading 00 but no actual dial code.

### ISSUE THREAD

**Issue by matteoredz** [floere/phony#514]
Important fact: *Phony only works with international phone numbers.* It needs the country code to be able to identify the number's country and rules.

Gem versions:
  * phony (2.20.8)
  * phony_rails (0.14.13)

What I did
----------

I called the `normalize_number` on a GB phone number with leading 00 but no 44 dial code, so `007533006408`, as follows:

```ruby
PhonyRails.normalize_number "007533006408", country_code: "GB"
```

What happened
-------------

The method returned `7533006408`

What I expected to happen and why
---------------------------------

I would have expected the method to return `+447533006408`, with the `+44` GB prefix, as happens when I call the same exact method but with the `00447533006408` phone number, so:

```ruby
PhonyRails.normalize_number "00447533006408", country_code: "GB"
# => "+447533006408"
```

**Comment by matteoredz** [comment]
Wrong repo, sorry 🙇🏻

**Comment by floere** [comment]
@matteoredz No worries!
