### ISSUE TITLE
Valid Italian Landline numbers fails plausibility check

### ISSUE THREAD

**Issue by TheRealJd3** [floere/phony#515]
What I did
----------
Attempted to save a valid phone number (+39 02832307418) on the latest gem version
![Screenshot 2023-10-13 at 10 45 08](https://github.com/floere/phony/assets/36233545/231994e8-ff1c-4cfc-ac45-0e64c9aab89e)

What happened
-------------
Failed to save a Italian landline number with area code two digit area codes (taking 02 and 06 as examples)
`irb(main):005:0> Phony.plausible?('+39 02832307418')
=> false`
`irb(main):006:0> Phony.plausible?('+3902832307418')
=> false`
`irb(main):007:0> Phony.plausible?('3902832307418')
=> false`
`irb(main):010:0> Phony.plausible?('+39 06832307418')
=> false`
`irb(main):011:0> Phony.plausible?('+3906832307418')
=> false`
`irb(main):012:0> Phony.plausible?('3906832307418')
=> false`

What I expected to happen and why
---------------------------------
It passes the plausibility check on valid numbers. According to wiki: Landline numbers start with the digit 0 and are 6 to 11 digits long, although they are rarely shorter than 9 digits

**Comment by floere** [comment]
Hi @TheRealJd3!

Thanks for the issue! 😊
Currently, Phony has the rule for the number after `02` or `06` as `/\A\d{8}\z/ => [4,4]`, so max. 8 digits, excluding the `0X`. This means, 9 digits after the `0X` is not valid.

Would you feel up to the task of extending the phone number scheme for Italy in a PR?
