### ISSUE TITLE
Valid phone numbers of Luxembourg don't pass the plausibility check

### ISSUE THREAD

**Issue by yoshih** [floere/phony#520]
Hi there!

What I did
----------

* I tried to save valid phone numbers of Luxembourg ("LU") with Phony Rails:
E.g.
+3522634731 (https://www.khn.lu/)
+3522620521 (https://www.neimenster.lu/en/home/)
- I also performed a plausibility check with Phony directly:
```ruby
Phony.plausible?("+3522634731")
Phony.plausible?("+3522620521")
```

What happened
-------------

* the validations in Phony Rails failed (`improbable_phone`)
* in Phony, the numbers are recognized as _not_ plausible

What I expected to happen and why
---------------------------------

* since these are real phone numbers, I expected them to pass the plausibility check

Best regards
Yoshi

**Comment by floere** [comment]
@yoshih Hi! Thanks for the issue – do you feel up to making a PR for Luxembourg? Find the rules here: https://github.com/floere/phony/blob/master/lib/phony/countries.rb#L653-L663
