### ISSUE TITLE
Ruby = 2.7 is required

### ISSUE THREAD

**Issue by n-rodriguez** [floere/phony#530]
Hi there!

There is an issue here : https://github.com/floere/phony/blob/master/phony.gemspec#L9

It should be `s.required_ruby_version = '>= 2.7'`

Thanks for your work! 👍

**Comment by floere** [comment]
Good point, thanks! Are you using the gem from master branch?

**Comment by n-rodriguez** [comment]
I'd like :)

**Comment by n-rodriguez** [comment]
It runs in CI 👍

**Comment by floere** [comment]
> I'd like :)

Ok, but I suggest you fix the version you use to a commit SHA that works – I will sometimes push breaking code into the master branch.

**Comment by n-rodriguez** [comment]
> Ok, but I suggest you fix the version you use to a commit SHA that works – I will sometimes push breaking code into the master branch.

Fine! Thank you!
